"""Sanity tests against real-listing HTML fixtures.

These tests skip when the fixture file is absent. The
.github/workflows/fetch-fixtures.yml workflow populates the files;
once that workflow has run on a branch the tests light up.

Coverage here is intentionally thin: we assert the fixture is
non-trivial, contains the per-source structural cue we'd expect, and
doesn't accidentally leak common PII patterns that the anonymization
step is supposed to scrub. The richer "given real HTML, does Claude
extract the right fields" test belongs in a live-LLM smoke run, not
in the standard suite (would burn API credit on every push).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from scraper.source_parsers import bezrealitky, common, idnes_reality, remax

_FIXTURE_DIR = (
    Path(__file__).parent.parent.parent / "fixtures" / "source_html"
)


def _fixture_or_skip(name: str) -> str:
    path = _FIXTURE_DIR / name
    if not path.exists():
        pytest.skip(
            f"fixture {path.name} not present; "
            f"run the fetch-fixtures workflow to populate it"
        )
    return path.read_text(encoding="utf-8")


def _assert_fixture_well_formed(html: str) -> None:
    assert html.startswith("<!-- ANONYMIZED FIXTURE"), (
        "fixture missing the anonymization banner; was it generated by "
        "scripts/fetch_and_anonymize_fixtures.py?"
    )
    assert len(html) > 5_000, "fixture suspiciously small for a real listing"


def _assert_no_common_pii(html: str) -> None:
    """Anonymization sanity. Not exhaustive — agent names slip through."""
    # Known phone formats should be scrubbed.
    assert not re.search(r"\+?420[\s ]?\d{3}[\s ]?\d{3}[\s ]?\d{3}", html)
    # Emails, except the placeholder.
    leaked_emails = [
        m.group(0)
        for m in re.finditer(r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}", html)
        if m.group(0) != "agent@example.cz"
    ]
    assert leaked_emails == [], f"unscrubbed email(s): {leaked_emails[:3]}"


# ----------------------------------------------------------------------
# Per-source fixtures
# ----------------------------------------------------------------------

def test_bezrealitky_fixture_well_formed():
    html = _fixture_or_skip("bezrealitky_sample.html")
    _assert_fixture_well_formed(html)
    _assert_no_common_pii(html)
    # bezrealitky listings always include a Czech price label.
    assert "Cena" in html or "cena" in html.lower()


def test_idnes_reality_fixture_well_formed():
    html = _fixture_or_skip("idnes_reality_sample.html")
    _assert_fixture_well_formed(html)
    _assert_no_common_pii(html)
    # reality.idnes.cz lists the disposition and area in the spec table.
    assert "plocha" in html.lower()


def test_remax_fixture_well_formed():
    html = _fixture_or_skip("remax_sample.html")
    _assert_fixture_well_formed(html)
    _assert_no_common_pii(html)
    # remax-czech.cz pages always advertise the Remax brand somewhere.
    assert "RE/MAX" in html or "remax" in html.lower()


# ----------------------------------------------------------------------
# Per-source build_messages renders against the real HTML
# (asserts no encoding / template explosions on real pages)
# ----------------------------------------------------------------------

@pytest.mark.parametrize("module,fixture_name,url", [
    (bezrealitky, "bezrealitky_sample.html",
     "https://www.bezrealitky.cz/sample"),
    (idnes_reality, "idnes_reality_sample.html",
     "https://reality.idnes.cz/sample"),
    (remax, "remax_sample.html",
     "https://www.remax-czech.cz/sample"),
])
def test_build_messages_renders_against_real_html(module, fixture_name, url):
    html = _fixture_or_skip(fixture_name)
    msgs = module.build_messages(url, html)
    assert len(msgs) == 1
    content = msgs[0]["content"]
    assert url in content
    # Either the full HTML or the truncated cap.
    truncated, was_truncated = common.truncate_html(html)
    assert truncated in content
    if was_truncated:
        assert "truncated" in content
