"""Hand-read metadata for the C2 tables: what each feature measures and who reads it outside the
model (live decision paths only; judge.py digests, model.py hand priors and errors.py are not
decision paths). Line numbers: origin/main b2454fa1."""

MEANS = {
    "area_rel_diff": "|a-b|/max of stored area_m2 (<=0.08 after wall E5)",
    "area_exact": "area within 1% or 0.5 m2",
    "dispo_equal": "disposition equal (always 1 when present: wall E5-dispo vetoes unequal)",
    "floor_diff": "|floor a - floor b| (<=1 for flats after the floor wall)",
    "total_floors_equal": "total_floors equal",
    "attr_agreements": "count of equal categorical attrs (14 keys, conflated 0.5)",
    "attr_contradictions": "count of differing categorical attrs",
    "attr_agreements_rare": "agreements weighted by in-block rarity",
    "price_last_ratio": "min/max current price",
    "ppm2_rel_diff": "rel. diff of price per stored m2",
    "price_path_event_match": "same-day same-size price change events matched",
    "jaccard_shingle": "5-shingle Jaccard of descriptions",
    "containment_max": "shingle containment, max of both directions",
    "tfidf_cos": "tf-idf cosine (block or corpus idf)",
    "simhash_hamming": "64-bit SimHash Hamming",
    "len_ratio": "description length ratio",
    "rare_token_overlap": "shared in-block rare tokens (cap 5, block>=20 docs)",
    "numeric_fact_overlap": "agreeing (value,unit) numerals in text",
    "numeral_conflict": "conflicting floor/rooms/unit numerals in text",
    "same_broker_key": "same hashed broker contact key",
    "same_broker_identity": "same resolved broker identity",
    "broker_known_both": "both broker keys known (presence as value)",
    "same_ruian_adm_kod": "same RUIAN address point",
    "same_street_key": "same street key",
    "same_house_number": "same house number",
    "same_psc": "same postcode",
    "dist_norm": "pin distance / (r_a+r_b+25 m), street grain only",
    "same_exact_pin": "identical pin key",
    "pin_pop": "log1p adverts on the pin",
    "phash_tight_matches": "1:1 dHash matches <=6 bits (non-stock, <=30/side)",
    "phash_loose_matches": "1:1 dHash matches <=11 bits",
    "phash_match_ratio": "tight matches / min gallery",
    "clip_max_cos": "best CLIP cosine, 8x8 frames",
    "clip_mean_top3_cos": "mean of top-3 CLIP cosines",
    "seq_monotone_ratio": "matched frames in gallery order",
    "interior_match_ratio": "tight matches among CLIP-interior frames",
    "exterior_match_ratio": "tight matches among CLIP-exterior frames",
    "plan_match_ratio": "tight matches among CLIP-plan frames",
    "catalog_ratio_max": "max stock share (E9) of the two galleries",
    "n_images_min": "min non-stock gallery size",
    "gap_days": "days between the live windows",
    "overlap_days": "days co-live",
    "both_active": "both active now",
    "same_source": "same portal",
    "unit_number_shared": "same unit number in text numerals",
    "plot_area_rel_diff": "rel. diff of plot (estate/land headline)",
    "plot_area_exact": "plot within 2%",
    "tag_rooms_both": "# CLIP top-tags both galleries show",
    "tag_rooms_private": "# private rooms (interior minus hallway) both show",
    "tag_tight_matches": "# shared tags whose best same-tag dHash <=6",
    "tag_dhash_min": "min over shared tags of best same-tag dHash",
    "tag_clip_mean": "mean over shared tags of best same-tag cosine",
    "tag_clip_min": "min over shared tags of best same-tag cosine",
    "tag_room_clip_min": "min over private rooms of best cosine",
    "tag_room_clip_min2": "2nd-weakest private room cosine",
    "tag_lookalike_share": "share of shared tags cos>=0.80 but dHash>11",
    "floorplan_tight_match": "floor_plan tag present both, dHash<=6",
    "floorplan_conflict": "floor_plan tag both, dHash>11",
    "floor_stated_conflict": "same portal and floor gap exactly 1",
    "ref_code_shared": "same rare agency order code in both bodies (NOT in the model)",
}

# Live consumers outside the logistic model. (off) = the path is switched off under w31.
CONSUMERS = {
    "area_rel_diff": "K-B <=1% decide.py:194; K-C <=3% decide.py:213; E63 <=1% decide.py:466; K-A(off) decide.py:145; E11 ATTR features.py:407-409",
    "area_exact": "E11 ATTR features.py:407; interaction x dispo_equal",
    "dispo_equal": "K-C decide.py:222; K-A(off) decide.py:149; E11 ATTR features.py:409",
    "floor_diff": "K-A(off) decide.py:146; E45(off) decide.py:308; builds floor_stated_conflict features.py:1659",
    "total_floors_equal": "model only",
    "attr_agreements": "model only",
    "attr_contradictions": "auto-reject >=3 decide.py:437",
    "attr_agreements_rare": "E11 ATTR >=4 features.py:410",
    "price_last_ratio": "E63 >=0.995 decide.py:469",
    "ppm2_rel_diff": "model only",
    "price_path_event_match": "D50 corroboration 'price_path' demonstrate.py:622 (two_of mode only; w31 = unit, so dead)",
    "jaccard_shingle": "model only",
    "containment_max": "K-B >=0.90 decide.py:195; E63 >=0.90 decide.py:472; D50 body >=0.80 demonstrate.py:615; E164 strong body >=0.98 demonstrate.py:697; twin >=0.99 demonstrate.py:288; E45(off) decide.py:294",
    "tfidf_cos": "model only",
    "simhash_hamming": "model only (the blocking text probe uses the simhash bands, not this feature)",
    "len_ratio": "model only",
    "rare_token_overlap": "E11 TXT >=2 features.py:429; E45(off) decide.py:320",
    "numeric_fact_overlap": "E11 TXT >=2 features.py:430",
    "numeral_conflict": "auto-reject decide.py:440",
    "same_broker_key": "K-B decide.py:199; E11 BRK; E45/E46/E47(off) decide.py:297,375,399",
    "same_broker_identity": "E11 BRK features.py:436",
    "broker_known_both": "model only",
    "same_ruian_adm_kod": "E11 LOC; K-A(off) decide.py:148; E45(off) decide.py:307; D50 'pin' demonstrate.py:620 (two_of only)",
    "same_street_key": "E11 LOC",
    "same_house_number": "E11 LOC",
    "same_psc": "model only",
    "dist_norm": "E11 LOC <=1",
    "same_exact_pin": "E11 LOC; D50 'pin' demonstrate.py:619 (two_of only)",
    "pin_pop": "model only (+ lane calibration census incremental.py:407)",
    "phash_tight_matches": "K-C >=4 decide.py:211; D50 photo >=1 demonstrate.py:613; E164 strong >=3 demonstrate.py:693; D43 promote photo warrant + E243 interior exemption indistinguishable.py:378; cellar yield >=4 indistinguishable.py:1277; cluster slot indistinguishable.py:205; E11 IMG",
    "phash_loose_matches": "K-B image floor E65(off) decide.py:184",
    "phash_match_ratio": "E11 IMG >=0.30",
    "clip_max_cos": "E11 IMG >=0.95",
    "clip_mean_top3_cos": "model only",
    "seq_monotone_ratio": "K-C >=0.80 decide.py:212; E11 IMG",
    "interior_match_ratio": "E11 IMG >=0.01; E45/E46/E63-interior(off) decide.py:281,372,476",
    "exterior_match_ratio": "model only",
    "plan_match_ratio": "model only",
    "catalog_ratio_max": "K-C <=0.20 decide.py:214; E11 IMG; E46(off) decide.py:371",
    "n_images_min": "E65/E45/E63-interior(off) decide.py:180,282,477",
    "gap_days": "model only",
    "overlap_days": "E45/E46/E47(off) decide.py:300,370,396",
    "both_active": "model only",
    "same_source": "K-B decide.py:198; stratum side decide.py:414 (both model strata 0.9788, so inert)",
    "unit_number_shared": "E45/E47(off) decide.py:309,402",
    "plot_area_rel_diff": "model only",
    "plot_area_exact": "E11 ATTR",
    "tag_rooms_both": "model only",
    "tag_rooms_private": "model only",
    "tag_tight_matches": "model only",
    "tag_dhash_min": "model only",
    "tag_clip_mean": "model only",
    "tag_clip_min": "model only",
    "tag_room_clip_min": "model only",
    "tag_room_clip_min2": "D43 interior/floorplan facts <0.90 indistinguishable.py:3093; agreeing attr room_photo indistinguishable.py:3181; E164 strong rooms>=0.90 demonstrate.py:694; cluster slot",
    "tag_lookalike_share": "model only",
    "floorplan_tight_match": "model only",
    "floorplan_conflict": "D43 floorplan fact indistinguishable.py:3092; cluster slot",
    "floor_stated_conflict": "model only",
    "ref_code_shared": "K-R decide.py:241; D50 code demonstrate.py:617; E164 strong code demonstrate.py:685; E11 TXT",
}

# Reader -> (code line of its add(), tolerance / predicate, what it repeats elsewhere).
READER_META = {
    "category_type": ("indistinguishable.py:2621", "deal type differs", "WALL E2 guards.py:71 + cluster invariant guards.py (deal-type mix)"),
    "category_main": ("indistinguishable.py:2625", "kind incompatible (dum<->komercni allowed)", "WALL E3 guards.py:73 + cluster invariant"),
    "area": ("indistinguishable.py:2638", "gate/cluster >8% (d43_gate_area_tol); promote area_relation band/reject >3%", "WALL E5 8% guards.py:75 (gate reading is the wall exactly); cluster invariant area_spread 8%; D50 A:area; agreeing attr 'area'; features area_rel_diff/area_exact; K-B 1%/K-C 3%/E63 1%"),
    "stated_area": ("indistinguishable.py:2646", "sets of printed areas disjoint (structural_truth.areas_disjoint)", "printed_area/headline_area/offer_area readers; agreeing attr 'stated_area'"),
    "disposition": ("indistinguishable.py:2651", "differs, land exempt", "WALL guards.py:79 identical predicate (fires only at cluster grain); D50 A:disposition; feature dispo_equal (constant); K-C"),
    "floor": ("indistinguishable.py:2659 (_floor_fact :2404)", "residual gap after floor camps; 1 storey inside one feed", "WALL floor >=2 flats guards.py:83; features floor_diff, floor_stated_conflict; numeral_conflict floor slot (auto-reject); prose_floor/subject_floor/storey_word/offered_storey"),
    "total_floors": ("indistinguishable.py:2680", "any delta not explained by camps / 1-storey ambiguity (lenient)", "feature total_floors_equal; agreeing attr"),
    "plot_area": ("indistinguishable.py:2684 (_plot_conflict :622)", "plots apart >2% (PLOT_TOL) with truncation/echo excuses", "features plot_area_rel_diff/plot_area_exact (2%); E11 ATTR; plot_prose/plot_prose_exact/priced_row/parcel/part_whole"),
    "price": ("indistinguishable.py:2712", ">5% cross / >60% same portal, excused by path (0.5%), per-m2 path, sequential move; co-live contradiction", "features price_last_ratio/ppm2/price_path_event_match; D50 A:price (exact); cluster price limb E157 (d43.py:98); E63 price ratio"),
    "obec": ("indistinguishable.py:2732", "obec codes differ, both at street grain", "blocking key; D50 A:obec; obec_prose/body_obec"),
    "street": ("indistinguishable.py:2737", "street keys differ unless pins <=15 m (lenient)", "feature same_street_key + E11 LOC; agreeing attr 'street'; street_prose"),
    "orientation": ("indistinguishable.py:2744", "one compass word each, differ", "agreeing attr 'orientation'"),
    "unit_designator": ("indistinguishable.py:2749", "one designator each, differ, same address block", "E61 VETO guards.py:87-115 identical predicate (vetoed first, so never reached at pair grain)"),
    "parcel": ("indistinguishable.py:2758", "selected parcel sets conflict", "plot readers"),
    "accessory": ("indistinguishable.py:2765", "garage/cellar numbers conflict", "unit-code family"),
    "extent": ("indistinguishable.py:2772 (offered_extent :1466)", "different quantity offered", "extent_package/extent_variant"),
    "two_unit": ("indistinguishable.py:2775 (:479)", "area and price both moved (0.5% tols)", "area + price readers together"),
    "printed_area": ("indistinguishable.py:2784 (:509)", "body headline areas conflict by rounding rule", "stated_area/headline_area/offer_area; D50 area"),
    "offer_area": ("indistinguishable.py:2794 (:672)", "lead size ratio >=2", "OFF in w31 (d43_offer_area false)"),
    "prose_floor": ("indistinguishable.py:2851", "printed storeys disjoint, gap>=2 or 1 in feed", "floor family"),
    "subject_floor": ("indistinguishable.py:2863", "offered unit's storey clause differs", "floor family"),
    "storey_word": ("indistinguishable.py:2873", "prizemi vs v patre", "floor family"),
    "unit_count": ("indistinguishable.py:2887", "stated dwelling counts differ (co-live + no path)", "-"),
    "unit_code": ("indistinguishable.py:2893", "printed unit codes conflict", "body_align; english/slug/labelled/space/designator readers; E61"),
    "street_prose": ("indistinguishable.py:2901 (:551)", "bodies name streets, none in common", "street"),
    "obec_prose": ("indistinguishable.py:2903 (:564)", "bodies print own town, not other's", "obec/body_obec; D50 A:obec"),
    "agency_code": ("indistinguishable.py:2909 (:1009)", "two order codes, co-live, two bodies", "OFF (refuted D61); K-R reads the same codes"),
    "charge": ("indistinguishable.py:2915 (:1041)", "second tenancy number beside a price gap", "price"),
    "plot_prose": ("indistinguishable.py:2921 (:1070)", "two land packages priced apart", "plot family"),
    "labelled_unit": ("indistinguishable.py:2928", "labelled unit ids conflict", "unit-code family"),
    "headline_area": ("indistinguishable.py:2933 (:1129)", "commercial lead size vs own column, same source, co-live, gap>=10%", "area family"),
    "offered_storey": ("indistinguishable.py:2938 (:1199)", "letting storey on NP scale", "floor family"),
    "accessory_area": ("indistinguishable.py:2943 (:1227)", "cellar sizes (co-live only)", "cellar_area (same fact, second reader)"),
    "cellar_area": ("indistinguishable.py:2947 (:1252)", "flat cellar sizes apart beyond tolerance; yields to >=4 tight frames + agreeing paths", "accessory_area"),
    "body_obec": ("indistinguishable.py:2952 (:1293)", "place body names vs filed place", "obec family"),
    "plot_prose_exact": ("indistinguishable.py:2957 (:1336)", "body plot at exact bar", "plot family"),
    "priced_row": ("indistinguishable.py:2962 (:1379)", "seller's land price-list row", "plot family"),
    "neighbour_plot": ("indistinguishable.py:2967 (:1399)", "difference between two plots both on offer", "plot family"),
    "part_whole": ("indistinguishable.py:2972 (:1095)", "part vs whole parcel", "plot family"),
    "rental_colive": ("indistinguishable.py:2977 (:1543)", "two co-live lets parted by one stated detail (8 sub-dials)", "-"),
    "english_unit_code": ("indistinguishable.py:2982 (:2033)", "English unit code conflicts", "unit-code family"),
    "slug_unit": ("indistinguishable.py:2986 (:2051)", "unit code / size in the portal URL", "unit-code family"),
    "agency_code_plus": ("indistinguishable.py:2991 (:2086)", "two order codes + one more difference", "agency_code"),
    "offered_use": ("indistinguishable.py:2995 (:2131)", "stated use of co-live spaces", "-"),
    "commercial_subtype": ("indistinguishable.py:2999 (:2150)", "portal subtype of co-live lets", "OFF in w31"),
    "plot_attribute": ("indistinguishable.py:3004 (:2166)", "plot dropdown value, co-live", "plot family"),
    "product_class": ("indistinguishable.py:3009 (:2196)", "desk vs office", "-"),
    "space_number": ("indistinguishable.py:3014 (:2220)", "commercial space numbers", "unit-code family"),
    "part_addition": ("indistinguishable.py:3019 (:2250)", "lead with different parts of one column", "area family"),
    "printed_house_number": ("indistinguishable.py:3024 (:1764)", "bodies print two houses of one street", "stored_house_number"),
    "stored_house_number": ("indistinguishable.py:3029 (:1826)", "resolver house number, guarded", "feature same_house_number"),
    "printed_designator": ("indistinguishable.py:3034 (:1877)", "designator noun inflections", "unit_designator/E61"),
    "plan_space": ("indistinguishable.py:3039 (:2024)", "room of a priced letting plan", "space_number"),
    "extent_variant": ("indistinguishable.py:3044 (:1424)", "row of an extent menu", "extent family"),
    "lot_label": ("indistinguishable.py:3049 (:1898)", "lot label A13 vs A14", "unit-code family"),
    "extent_package": ("indistinguishable.py:3054 (:1938)", "two packages each with extent+price", "extent family"),
    "agency_code_colive": ("indistinguishable.py:3059 (:1969)", "two codes one portal, paths never meet", "OFF in w31"),
    "outdoor_accessory": ("indistinguishable.py:3064 (:2514)", "balcony/terrace size apart (co-live)", "accessory_price"),
    "accessory_price": ("indistinguishable.py:3067 (:2539)", "accessory sizes apart + prices never joined", "outdoor_accessory + price"),
    "position_designator": ("indistinguishable.py:3072 (:2561)", "half/side/position", "unit-code family"),
    "named_villa": ("indistinguishable.py:3077 (:2577)", "named villa / residence code", "OFF in w31"),
    "body_align": ("indistinguishable.py:3086 (body_align.py)", "aligned bodies differ in a unit token (min ratio 0.60)", "every unit-code reader (it is their generic form)"),
    "floorplan": ("indistinguishable.py:3096", "floorplan_conflict and room cos2 <0.90 (cluster only)", "features floorplan_conflict + tag_room_clip_min2"),
    "interior": ("indistinguishable.py:3107", "tag_room_clip_min2 <0.90, no tight frame, not a one-text re-post (cluster only)", "feature tag_room_clip_min2; E164 rooms>=0.90; agreeing attr room_photo"),
}
