"""Hand-read metadata for the C2 tables: what each feature measures and who reads it outside the
model (live decision paths only; judge.py digests, model.py hand priors and errors.py are not
decision paths). Line numbers: origin/main b2454fa1."""

MEANS = {
    "area_rel_diff": "|a-b|/max of stored area_m2 (<=0.08 after wall E5)",
    "area_exact": "area within 1% or 0.5 m2",
    "dispo_equal": "disposition equal (always 1 when present: wall E5-dispo vetoes unequal)",
    "floor_diff": "|floor a - floor b| (<=1 for flats after the floor wall)",
    "total_floors_equal": "total_floors equal",
    "attr_agreements": "count of equal categorical attrs (14 keys, conflated 0.5)",
    "attr_contradictions": "count of differing categorical attrs",
    "attr_agreements_rare": "agreements weighted by in-block rarity",
    "price_last_ratio": "min/max current price",
    "ppm2_rel_diff": "rel. diff of price per stored m2",
    "price_path_event_match": "same-day same-size price change events matched",
    "jaccard_shingle": "5-shingle Jaccard of descriptions",
    "containment_max": "shingle containment, max of both directions",
    "tfidf_cos": "tf-idf cosine (block or corpus idf)",
    "simhash_hamming": "64-bit SimHash Hamming",
    "len_ratio": "description length ratio",
    "rare_token_overlap": "shared in-block rare tokens (cap 5, block>=20 docs)",
    "numeric_fact_overlap": "agreeing (value,unit) numerals in text",
    "numeral_conflict": "conflicting floor/rooms/unit numerals in text",
    "same_broker_key": "same hashed broker contact key",
    "same_broker_identity": "same resolved broker identity",
    "broker_known_both": "both broker keys known (presence as value)",
    "same_ruian_adm_kod": "same RUIAN address point",
    "same_street_key": "same street key",
    "same_house_number": "same house number",
    "same_psc": "same postcode",
    "dist_norm": "pin distance / (r_a+r_b+25 m), street grain only",
    "same_exact_pin": "identical pin key",
    "pin_pop": "log1p adverts on the pin",
    "phash_tight_matches": "1:1 dHash matches <=6 bits (non-stock, <=30/side)",
    "phash_loose_matches": "1:1 dHash matches <=11 bits",
    "phash_match_ratio": "tight matches / min gallery",
    "clip_max_cos": "best CLIP cosine, 8x8 frames",
    "clip_mean_top3_cos": "mean of top-3 CLIP cosines",
    "seq_monotone_ratio": "matched frames in gallery order",
    "interior_match_ratio": "tight matches among CLIP-interior frames",
    "exterior_match_ratio": "tight matches among CLIP-exterior frames",
    "plan_match_ratio": "tight matches among CLIP-plan frames",
    "catalog_ratio_max": "max stock share (E9) of the two galleries",
    "n_images_min": "min non-stock gallery size",
    "gap_days": "days between the live windows",
    "overlap_days": "days co-live",
    "both_active": "both active now",
    "same_source": "same portal",
    "unit_number_shared": "same unit number in text numerals",
    "plot_area_rel_diff": "rel. diff of plot (estate/land headline)",
    "plot_area_exact": "plot within 2%",
    "tag_rooms_both": "# CLIP top-tags both galleries show",
    "tag_rooms_private": "# private rooms (interior minus hallway) both show",
    "tag_tight_matches": "# shared tags whose best same-tag dHash <=6",
    "tag_dhash_min": "min over shared tags of best same-tag dHash",
    "tag_clip_mean": "mean over shared tags of best same-tag cosine",
    "tag_clip_min": "min over shared tags of best same-tag cosine",
    "tag_room_clip_min": "min over private rooms of best cosine",
    "tag_room_clip_min2": "2nd-weakest private room cosine",
    "tag_lookalike_share": "share of shared tags cos>=0.80 but dHash>11",
    "floorplan_tight_match": "floor_plan tag present both, dHash<=6",
    "floorplan_conflict": "floor_plan tag both, dHash>11",
    "floor_stated_conflict": "same portal and floor gap exactly 1",
    "ref_code_shared": "same rare agency order code in both bodies (NOT in the model)",
}

# Live consumers outside the logistic model. (off) = the path is switched off under w31.
CONSUMERS = {
    "area_rel_diff": "K-B <=1% decide.py:194; K-C <=3% decide.py:213; E63 <=1% decide.py:466; K-A(off) decide.py:145; E11 ATTR features.py:407-409",
    "area_exact": "E11 ATTR features.py:407; interaction x dispo_equal",
    "dispo_equal": "K-C decide.py:222; K-A(off) decide.py:149; E11 ATTR features.py:409",
    "floor_diff": "K-A(off) decide.py:146; E45(off) decide.py:308; builds floor_stated_conflict features.py:1659",
    "total_floors_equal": "model only",
    "attr_agreements": "model only",
    "attr_contradictions": "auto-reject >=3 decide.py:437",
    "attr_agreements_rare": "E11 ATTR >=4 features.py:410",
    "price_last_ratio": "E63 >=0.995 decide.py:469",
    "ppm2_rel_diff": "model only",
    "price_path_event_match": "D50 corroboration 'price_path' demonstrate.py:622 (two_of mode only; w31 = unit, so dead)",
    "jaccard_shingle": "model only",
    "containment_max": "K-B >=0.90 decide.py:195; E63 >=0.90 decide.py:472; D50 body >=0.80 demonstrate.py:615; E164 strong body >=0.98 demonstrate.py:697; twin >=0.99 demonstrate.py:288; E45(off) decide.py:294",
    "tfidf_cos": "model only",
    "simhash_hamming": "model only (the blocking text probe uses the simhash bands, not this feature)",
    "len_ratio": "model only",
    "rare_token_overlap": "E11 TXT >=2 features.py:429; E45(off) decide.py:320",
    "numeric_fact_overlap": "E11 TXT >=2 features.py:430",
    "numeral_conflict": "auto-reject decide.py:440",
    "same_broker_key": "K-B decide.py:199; E11 BRK; E45/E46/E47(off) decide.py:297,375,399",
    "same_broker_identity": "E11 BRK features.py:436",
    "broker_known_both": "model only",
    "same_ruian_adm_kod": "E11 LOC; K-A(off) decide.py:148; E45(off) decide.py:307; D50 'pin' demonstrate.py:620 (two_of only)",
    "same_street_key": "E11 LOC",
    "same_house_number": "E11 LOC",
    "same_psc": "model only",
    "dist_norm": "E11 LOC <=1",
    "same_exact_pin": "E11 LOC; D50 'pin' demonstrate.py:619 (two_of only)",
    "pin_pop": "model only (+ lane calibration census incremental.py:407)",
    "phash_tight_matches": "K-C >=4 decide.py:211; D50 photo >=1 demonstrate.py:613; E164 strong >=3 demonstrate.py:693; D43 promote photo warrant + E243 interior exemption indistinguishable.py:378; cellar yield >=4 indistinguishable.py:1277; cluster slot indistinguishable.py:205; E11 IMG",
    "phash_loose_matches": "K-B image floor E65(off) decide.py:184",
    "phash_match_ratio": "E11 IMG >=0.30",
    "clip_max_cos": "E11 IMG >=0.95",
    "clip_mean_top3_cos": "model only",
    "seq_monotone_ratio": "K-C >=0.80 decide.py:212; E11 IMG",
    "interior_match_ratio": "E11 IMG >=0.01; E45/E46/E63-interior(off) decide.py:281,372,476",
    "exterior_match_ratio": "model only",
    "plan_match_ratio": "model only",
    "catalog_ratio_max": "K-C <=0.20 decide.py:214; E11 IMG; E46(off) decide.py:371",
    "n_images_min": "E65/E45/E63-interior(off) decide.py:180,282,477",
    "gap_days": "model only",
    "overlap_days": "E45/E46/E47(off) decide.py:300,370,396",
    "both_active": "model only",
    "same_source": "K-B decide.py:198; stratum side decide.py:414 (both model strata 0.9788, so inert)",
    "unit_number_shared": "E45/E47(off) decide.py:309,402",
    "plot_area_rel_diff": "model only",
    "plot_area_exact": "E11 ATTR",
    "tag_rooms_both": "model only",
    "tag_rooms_private": "model only",
    "tag_tight_matches": "model only",
    "tag_dhash_min": "model only",
    "tag_clip_mean": "model only",
    "tag_clip_min": "model only",
    "tag_room_clip_min": "model only",
    "tag_room_clip_min2": "D43 interior/floorplan facts <0.90 indistinguishable.py:3093; agreeing attr room_photo indistinguishable.py:3181; E164 strong rooms>=0.90 demonstrate.py:694; cluster slot",
    "tag_lookalike_share": "model only",
    "floorplan_tight_match": "model only",
    "floorplan_conflict": "D43 floorplan fact indistinguishable.py:3092; cluster slot",
    "floor_stated_conflict": "model only",
    "ref_code_shared": "K-R decide.py:241; D50 code demonstrate.py:617; E164 strong code demonstrate.py:685; E11 TXT",
}
