"""Fetch real listing pages and save anonymized fixtures.

Run from GitHub Actions (.github/workflows/fetch-fixtures.yml). Cannot
run from this developer sandbox because outbound HTTP is blocked.

Anonymization scope: drop contact PII (phones, emails) and exact
street numbers. Listing prices, dispositions, and the surrounding
HTML structure are preserved — they're public data and the parser
tests need them to make meaningful assertions later. Site-specific
agent-name patterns are too varied to scrub by regex without false
positives; if a fixture contains a real agent name, scrub it
manually post-fetch.

Usage (from a workflow runner):

    python scripts/fetch_and_anonymize_fixtures.py \\
        --output-dir tests/fixtures/source_html \\
        --bezrealitky https://www.bezrealitky.cz/... \\
        --idnes https://reality.idnes.cz/detail/... \\
        --remax https://www.remax-czech.cz/reality/... \\
        --bazos-index https://reality.bazos.cz/prodam/byt/ \\
        --bazos-detail https://reality.bazos.cz/inzerat/.../...php

Each URL is optional; missing ones are skipped. Output filenames are
fixed (bezrealitky_sample.html etc.) so the per-source tests can find
them. Bazos is a bulk crawler source (not an LLM URL parser), so it
needs two fixtures — a search/index page and a single detail page.

Note: the regex anonymizer below scrubs phones/emails/street-numbers
but not agent/seller names (too varied for a safe regex). Bazos index
and detail pages embed real seller names in `odeslatakci('rating',…)`
onclicks and the "Jméno" field; hand-scrub those in the committed
fixture if present.

Second mode — scrub an ALREADY-SAVED fixture, contact fields only:

    python scripts/fetch_and_anonymize_fixtures.py \\
        --scrub-contacts tests/fixtures/<set>/*.html \\
        --name "<agent name as the page renders it>"

Use it for whole-page fixtures kept for their BYTES rather than for
their visible text — anonymize()'s blanket 9-digit sweep would rewrite
coordinates and photo ids there. See anonymize_contacts() below.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
import unicodedata
from pathlib import Path
from typing import Iterable, Sequence

import requests

LOG = logging.getLogger("fetch_fixtures")

USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
)
HEADERS = {
    "User-Agent": USER_AGENT,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "cs,en;q=0.7",
}

ANON_BANNER = (
    "<!-- ANONYMIZED FIXTURE — DO NOT TREAT AS REAL LISTING. "
    "Generated by scripts/fetch_and_anonymize_fixtures.py. -->\n"
)

# +420 XXX XXX XXX (and the 9-digit national format near contact context).
_PHONE_RE = re.compile(
    r"(?:\+?420[\s ]?)?"
    r"\d{3}[\s ]?\d{3}[\s ]?\d{3}",
)
_EMAIL_RE = re.compile(
    r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}",
)
# Czech address number format: '123/45a' or '123/45'. Replace with X/Y.
_STREET_NUM_RE = re.compile(r"\b(\d{1,4})/(\d{1,4}[a-z]?)\b")
# http(s) URLs are masked out before scrubbing — see anonymize().
_URL_RE = re.compile(r"https?://[^\s\"'<>]+")


def anonymize(html: str) -> str:
    # URLs are masked before scrubbing and restored after. Without this the scrubbers
    # silently CORRUPT image URLs: _PHONE_RE matches any 9 consecutive digits, so a
    # realitymix photo id becomes `nab_+420 XXX XXX XXX.jpg`, and _STREET_NUM_RE
    # matches any `N/M` pair, so an idnes CDN shard path `/thumbs/1/6/e/` becomes
    # `/thumbs/XXX/YY/e/`. That makes a fixture useless for testing media extraction —
    # the exact blind spot that let a 19-day gallery blackout ship green.
    # URLs carry no contact PII (mailto: is not http, so emails are still scrubbed).
    urls: list[str] = []

    def _mask(match: re.Match[str]) -> str:
        urls.append(match.group(0))
        return f"\x00URL{len(urls) - 1}\x00"

    out = _URL_RE.sub(_mask, html)
    out = _PHONE_RE.sub("+420 XXX XXX XXX", out)
    out = _EMAIL_RE.sub("agent@example.cz", out)
    out = _STREET_NUM_RE.sub("XXX/YY", out)
    out = re.sub(r"\x00URL(\d+)\x00", lambda m: urls[int(m.group(1))], out)
    return ANON_BANNER + out


# --- contact-scoped scrub, for fixtures anonymize() would corrupt ---
#
# anonymize() masks http(s) URLs and then sweeps EVERY 9-digit run. That is right
# for the LLM-parser fixtures, whose value is the visible listing text. It is
# wrong for a whole-page fixture kept for its BYTES (the location_w2a_refetch
# payload-normaliser set): on those pages the same 9-digit shape is a coordinate
# (`data-gps-lat="50.069672777778"`), a photo id inside JSON-escaped markup that
# the URL mask never sees (`\/foto\/32813\/75\/758874998f5b...`), or a Tailwind
# custom property (`--size:0.17813245890041`). Masking those destroys exactly the
# location signal such a fixture exists to prove survives normalisation.
#
# So this variant takes phone SEEDS from markup that says "phone" — a tel: href,
# schema.org "telephone", a rendered +420 group, a bare group that is a whole text
# node, a reveal-on-click data attribute — and then rewrites every rendering of
# those numbers. Emails and hand-supplied agent names go unconditionally. Same
# placeholders as anonymize(), so a fixture set stays consistent either way.
PHONE_PLACEHOLDER = "+420 XXX XXX XXX"
EMAIL_PLACEHOLDER = "agent@example.cz"
NAME_PLACEHOLDER = "Jan Novák"

CONTACT_BANNER = (
    "<!-- ANONYMIZED FIXTURE — phones, emails and agent names replaced with "
    "placeholders (scripts/fetch_and_anonymize_fixtures.py --scrub-contacts). "
    "Every other byte is the portal's. -->\n"
)
_BANNER_MARK = "ANONYMIZED FIXTURE"

# `\s` covers every separator a portal renders between digit groups, including
# the non-breaking and narrow spaces an editor shows as an ordinary space.
_SEP = r"[\s\-]?"
_GROUP9 = rf"\d{{3}}{_SEP}\d{{3}}{_SEP}\d{{3}}"
# A quote as an embedded-JSON payload can spell it: bare, HTML-entity-escaped
# (a JSON blob living inside an HTML attribute) or backslash-escaped (inside a JS
# string literal).
_JSON_Q = r'(?:&quot;|\\"|")'
_PHONE_SEED_RES: tuple[re.Pattern[str], ...] = (
    re.compile(r"tel:([+\d\s()\-]{9,20})"),
    re.compile(r'"telephone"\s*:\s*"([^"]{9,25})"'),
    re.compile(rf"(\+\s?420{_SEP}{_GROUP9})"),
    re.compile(rf">\s*(\+?(?:420{_SEP})?{_GROUP9})\s*<"),
    re.compile(rf'data-hidden-content-on-click="([^"]*{_GROUP9}[^"]*)"'),
    # A phone under a JSON KEY that says phone, with no `+420`, no digit grouping
    # and no tel: href to give it away — so every rule above walks straight past it.
    # mmreality is the case that found this: its whole detail payload is a Vue prop
    # inside an HTML attribute, and the agent block arrives as
    # `&quot;phone&quot;:&quot;731404040&quot;`. Longest alternative first, so
    # `phone_number` is not matched as `phone` + a failed closing quote.
    re.compile(
        rf"{_JSON_Q}(?:phone_number|mobile_phone|phone|mobile){_JSON_Q}\s*:\s*"
        rf"{_JSON_Q}([^\"&\\]{{9,25}}){_JSON_Q}"
    ),
)

# Cloudflare's "Email Address Obfuscation" rewrites every mailto: on the way out
# into a hex payload — the address XOR'd with a RANDOM LEADING KEY BYTE — carried in
# `data-cfemail` and in the /cdn-cgi/l/email-protection# href fragment. Three lines
# of Python reverse it, so a committed fixture carrying one publishes the address as
# surely as the plain text would, while matching no email or phone rule above.
# Re-encoding the PLACEHOLDER under the page's own key preserves the shape exactly —
# including the per-response key that is mmreality's entire measured churn — so the
# fixture still proves what it was fetched to prove.
_CFEMAIL_RE = re.compile(
    r'(data-cfemail="|/cdn-cgi/l/email-protection#)([0-9a-fA-F]{4,})'
)


def _cf_encode(plaintext: str, key: int) -> str:
    return f"{key:02x}" + "".join(f"{ord(c) ^ key:02x}" for c in plaintext)


def _scrub_cf_emails(html: str) -> str:
    def replace(match: re.Match[str]) -> str:
        payload = match.group(2)
        if len(payload) % 2:
            return match.group(0)
        return match.group(1) + _cf_encode(EMAIL_PLACEHOLDER, int(payload[:2], 16))

    return _CFEMAIL_RE.sub(replace, html)


def phone_seeds(html: str) -> set[str]:
    """The 9-digit national numbers this page presents AS phone numbers."""
    seeds: set[str] = set()
    for pattern in _PHONE_SEED_RES:
        for match in pattern.finditer(html):
            digits = re.sub(r"\D", "", match.group(1))
            for prefix in ("00420", "420"):
                if len(digits) > 9 and digits.startswith(prefix):
                    digits = digits[len(prefix):]
                    break
            if len(digits) == 9:
                seeds.add(digits)
    return seeds


def _phone_pattern(digits: str) -> re.Pattern[str]:
    grouped = _SEP.join((digits[:3], digits[3:6], digits[6:]))
    # The lookarounds keep the seed from matching a longer digit run it happens to
    # sit inside (a timestamp, an id), which would leave a half-rewritten number.
    return re.compile(rf"(?<![\d/])(?:\+\s?420{_SEP}|00420{_SEP})?{grouped}(?!\d)")


def _json_escaped(text: str) -> str:
    return "".join(c if c.isascii() else f"\\u{ord(c):04x}" for c in text)


def _slugified(text: str) -> str:
    folded = "".join(
        c for c in unicodedata.normalize("NFD", text) if not unicodedata.combining(c)
    )
    return re.sub(r"[^a-z0-9]+", "-", folded.lower()).strip("-")


def _replace_name(html: str, name: str) -> str:
    # A name is not only rendered text: portals also carry it JSON-escaped inside
    # schema.org blocks (`Jan Nov\\u00e1k`) and slugged into a broker-profile URL
    # (`/makler/detail/jan-novak/`), and leaving either behind would undo the scrub.
    for variant, replacement in (
        (name, NAME_PLACEHOLDER),
        (_json_escaped(name), _json_escaped(NAME_PLACEHOLDER)),
        (_slugified(name), _slugified(NAME_PLACEHOLDER)),
    ):
        if variant:
            html = html.replace(variant, replacement)
    return html


def anonymize_contacts(html: str, *, names: Sequence[str] = ()) -> str:
    """Scrub contact PII only, leaving every other byte of the page intact.

    Covers the four shapes a Czech portal spells a contact in: rendered text, a
    tel:/mailto: href, an embedded-JSON field (plain, entity- or backslash-escaped),
    and a Cloudflare-obfuscated hex payload.

    Idempotent: the placeholders carry no phone digits and no name, and re-encoding
    the placeholder under a key it already carries returns the same bytes — so a
    second pass is a no-op, which is what lets a committed fixture be re-verified.
    """
    out = html
    for name in names:
        out = _replace_name(out, name)
    out = _EMAIL_RE.sub(EMAIL_PLACEHOLDER, out)
    out = _scrub_cf_emails(out)
    for digits in sorted(phone_seeds(out)):
        out = _phone_pattern(digits).sub(PHONE_PLACEHOLDER, out)
    if _BANNER_MARK not in out[:len(CONTACT_BANNER) + 200]:
        out = CONTACT_BANNER + out
    return out


def scrub_contacts_in_place(paths: Sequence[Path], names: Sequence[str]) -> int:
    for path in paths:
        original = path.read_text(encoding="utf-8")
        scrubbed = anonymize_contacts(original, names=names)
        if scrubbed != original:
            path.write_text(scrubbed, encoding="utf-8")
        LOG.info(
            "%s: %s (%d -> %d chars)",
            path, "scrubbed" if scrubbed != original else "already clean",
            len(original), len(scrubbed),
        )
    return 0


def fetch(url: str, *, timeout_s: float = 30.0) -> str:
    LOG.info("fetching %s", url)
    r = requests.get(url, headers=HEADERS, timeout=timeout_s)
    r.raise_for_status()
    return r.text


def write_fixture(html: str, output_path: Path) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = anonymize(html)
    output_path.write_text(body, encoding="utf-8")
    LOG.info("wrote %d chars to %s", len(body), output_path)
    return len(body)


def _process(
    url: str | None,
    out_path: Path,
    label: str,
    errors: list[str],
) -> None:
    if not url:
        LOG.info("[%s] no URL given; skipping", label)
        return
    try:
        html = fetch(url)
    except requests.HTTPError as exc:
        msg = f"[{label}] HTTP {exc.response.status_code}: {url}"
        LOG.error(msg)
        errors.append(msg)
        return
    except requests.RequestException as exc:
        msg = f"[{label}] fetch failed: {exc}"
        LOG.error(msg)
        errors.append(msg)
        return
    try:
        write_fixture(html, out_path)
    except OSError as exc:
        msg = f"[{label}] write failed: {exc}"
        LOG.error(msg)
        errors.append(msg)


def main(argv: Iterable[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output-dir", type=Path)
    p.add_argument("--bezrealitky", default=None)
    p.add_argument("--idnes", default=None)
    p.add_argument("--remax", default=None)
    p.add_argument("--bazos-index", default=None)
    p.add_argument("--bazos-detail", default=None)
    p.add_argument(
        "--scrub-contacts", nargs="+", type=Path, default=None, metavar="FIXTURE",
        help="rewrite these already-saved fixtures in place, contact fields only "
             "(no fetch); idempotent, so re-running proves a fixture is clean",
    )
    p.add_argument(
        "--name", action="append", default=[], metavar="NAME",
        help="an agent name to replace with the placeholder, in plain, "
             "JSON-escaped and slugged form (repeatable; applies to every file)",
    )
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if args.scrub_contacts:
        return scrub_contacts_in_place(args.scrub_contacts, args.name)
    if args.output_dir is None:
        p.error("--output-dir is required unless --scrub-contacts is given")

    errors: list[str] = []
    _process(
        args.bezrealitky,
        args.output_dir / "bezrealitky_sample.html",
        "bezrealitky", errors,
    )
    _process(
        args.idnes,
        args.output_dir / "idnes_reality_sample.html",
        "idnes_reality", errors,
    )
    _process(
        args.remax,
        args.output_dir / "remax_sample.html",
        "remax", errors,
    )
    _process(
        args.bazos_index,
        args.output_dir / "bazos_index_sample.html",
        "bazos_index", errors,
    )
    _process(
        args.bazos_detail,
        args.output_dir / "bazos_detail_sample.html",
        "bazos_detail", errors,
    )

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
