"""Fetch real listing pages and save anonymized fixtures.

Run from GitHub Actions (.github/workflows/fetch-fixtures.yml). Cannot
run from this developer sandbox because outbound HTTP is blocked.

Anonymization scope: drop contact PII (phones, emails) and exact
street numbers. Listing prices, dispositions, and the surrounding
HTML structure are preserved — they're public data and the parser
tests need them to make meaningful assertions later. Site-specific
agent-name patterns are too varied to scrub by regex without false
positives; if a fixture contains a real agent name, scrub it
manually post-fetch.

Usage (from a workflow runner):

    python scripts/fetch_and_anonymize_fixtures.py \\
        --output-dir tests/fixtures/source_html \\
        --bezrealitky https://www.bezrealitky.cz/... \\
        --idnes https://reality.idnes.cz/detail/... \\
        --remax https://www.remax-czech.cz/reality/... \\
        --bazos-index https://reality.bazos.cz/prodam/byt/ \\
        --bazos-detail https://reality.bazos.cz/inzerat/.../...php

Each URL is optional; missing ones are skipped. Output filenames are
fixed (bezrealitky_sample.html etc.) so the per-source tests can find
them. Bazos is a bulk crawler source (not an LLM URL parser), so it
needs two fixtures — a search/index page and a single detail page.

Note: the regex anonymizer below scrubs phones/emails/street-numbers
but not agent/seller names (too varied for a safe regex). Bazos index
and detail pages embed real seller names in `odeslatakci('rating',…)`
onclicks and the "Jméno" field; hand-scrub those in the committed
fixture if present.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path
from typing import Iterable

import requests

LOG = logging.getLogger("fetch_fixtures")

USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
)
HEADERS = {
    "User-Agent": USER_AGENT,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "cs,en;q=0.7",
}

ANON_BANNER = (
    "<!-- ANONYMIZED FIXTURE — DO NOT TREAT AS REAL LISTING. "
    "Generated by scripts/fetch_and_anonymize_fixtures.py. -->\n"
)

# +420 XXX XXX XXX (and the 9-digit national format near contact context).
_PHONE_RE = re.compile(
    r"(?:\+?420[\s ]?)?"
    r"\d{3}[\s ]?\d{3}[\s ]?\d{3}",
)
_EMAIL_RE = re.compile(
    r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}",
)
# Czech address number format: '123/45a' or '123/45'. Replace with X/Y.
_STREET_NUM_RE = re.compile(r"\b(\d{1,4})/(\d{1,4}[a-z]?)\b")


def anonymize(html: str) -> str:
    out = _PHONE_RE.sub("+420 XXX XXX XXX", html)
    out = _EMAIL_RE.sub("agent@example.cz", out)
    out = _STREET_NUM_RE.sub("XXX/YY", out)
    return ANON_BANNER + out


def fetch(url: str, *, timeout_s: float = 30.0) -> str:
    LOG.info("fetching %s", url)
    r = requests.get(url, headers=HEADERS, timeout=timeout_s)
    r.raise_for_status()
    return r.text


def write_fixture(html: str, output_path: Path) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = anonymize(html)
    output_path.write_text(body, encoding="utf-8")
    LOG.info("wrote %d chars to %s", len(body), output_path)
    return len(body)


def _process(
    url: str | None,
    out_path: Path,
    label: str,
    errors: list[str],
) -> None:
    if not url:
        LOG.info("[%s] no URL given; skipping", label)
        return
    try:
        html = fetch(url)
    except requests.HTTPError as exc:
        msg = f"[{label}] HTTP {exc.response.status_code}: {url}"
        LOG.error(msg)
        errors.append(msg)
        return
    except requests.RequestException as exc:
        msg = f"[{label}] fetch failed: {exc}"
        LOG.error(msg)
        errors.append(msg)
        return
    try:
        write_fixture(html, out_path)
    except OSError as exc:
        msg = f"[{label}] write failed: {exc}"
        LOG.error(msg)
        errors.append(msg)


def main(argv: Iterable[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output-dir", required=True, type=Path)
    p.add_argument("--bezrealitky", default=None)
    p.add_argument("--idnes", default=None)
    p.add_argument("--remax", default=None)
    p.add_argument("--bazos-index", default=None)
    p.add_argument("--bazos-detail", default=None)
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    errors: list[str] = []
    _process(
        args.bezrealitky,
        args.output_dir / "bezrealitky_sample.html",
        "bezrealitky", errors,
    )
    _process(
        args.idnes,
        args.output_dir / "idnes_reality_sample.html",
        "idnes_reality", errors,
    )
    _process(
        args.remax,
        args.output_dir / "remax_sample.html",
        "remax", errors,
    )
    _process(
        args.bazos_index,
        args.output_dir / "bazos_index_sample.html",
        "bazos_index", errors,
    )
    _process(
        args.bazos_detail,
        args.output_dir / "bazos_detail_sample.html",
        "bazos_detail", errors,
    )

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
