"""Emit `frontend/src/lib/workflowDocs.generated.ts` from the workflow YAML.

Single source of truth: the `.github/workflows/*.yml` files themselves.
This script parses each one and writes a typed TypeScript file the
frontend's Settings page imports to render the "GitHub Actions"
documentation section — so the docs can never drift from the real
workflows.

Per-workflow description is the FIRST PARAGRAPH of the leading `#`
comment block at the top of the file. Edit a workflow, edit its comment
in the same file, regenerate.

Run modes:

- `python scripts/generate_workflow_docs.py`  — emit the file.
- `python scripts/generate_workflow_docs.py --check` — exit non-zero if
  the on-disk file differs from what we'd generate. Wired into CI so a
  workflow edit without a regen fails the build.

The output is committed to the repo so Vite doesn't need to invoke
Python at build time. CI is the drift guard.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


HEADER = """\
// AUTOGENERATED — DO NOT EDIT.
// Source of truth: the .github/workflows/*.yml files.
// Regenerate with: python scripts/generate_workflow_docs.py
//
// CI runs `--check` and fails on drift, so adding, removing, or editing
// a workflow must be paired with a fresh regen in the same commit. The
// per-workflow `description` is the first paragraph of the leading
// comment block at the top of each YAML file.
"""

TS_TYPES = """\
export interface WorkflowInput {
  name: string;
  description: string;
  required: boolean;
  type: string;
  default: string | null;
  options: string[] | null;
}

export interface WorkflowSchedule {
  cron: string;
  human: string;
}

export interface WorkflowDoc {
  filename: string;
  name: string;
  description: string;
  manual: boolean;
  schedules: WorkflowSchedule[];
  onPush: boolean;
  onPullRequest: boolean;
  paths: string[] | null;
  inputs: WorkflowInput[];
  secrets: string[];
  concurrencyGroup: string | null;
  cancelInProgress: boolean | null;
  timeoutMinutes: number | null;
  permissions: string | null;
  runsUrl: string;
  sourceUrl: string;
}
"""

DEFAULT_SLUG = "waiff/sreality"
DEFAULT_BRANCH = "main"


def _repo_slug() -> str:
    try:
        url = subprocess.check_output(
            ["git", "config", "--get", "remote.origin.url"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return DEFAULT_SLUG
    url = url.removesuffix(".git")
    m = re.search(r"([^/:]+)/([^/]+)$", url)
    return f"{m.group(1)}/{m.group(2)}" if m else DEFAULT_SLUG


def _leading_description(text: str) -> str:
    """First paragraph of the leading `#` comment block (before `on:`)."""
    block: list[str] = []
    in_block = False
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("#"):
            in_block = True
            block.append(stripped.lstrip("#").strip())
        elif in_block:
            break
        elif raw.startswith(("on:", "jobs:")):
            break
        # else: name: line or blank line before the block — keep scanning.

    para: list[str] = []
    for line in block:
        if line == "":
            if para:
                break
            continue
        para.append(line)
    return " ".join(para)


def _describe_cron(expr: str) -> str:
    parts = expr.split()
    if len(parts) != 5:
        return expr
    minute, hour, dom, mon, dow = parts
    if dom != "*" or mon != "*" or dow != "*":
        return expr
    if hour == "*":
        if minute == "*":
            return "Every minute"
        if minute.startswith("*/"):
            return f"Every {minute[2:]} minutes"
        if minute == "0":
            return "Every hour (on the hour)"
        return f"Every hour at :{minute.zfill(2)}"
    if hour.startswith("*/"):
        suffix = "" if minute in ("0", "*") else f" at :{minute.zfill(2)}"
        return f"Every {hour[2:]} hours{suffix}"
    try:
        return f"Daily at {int(hour):02d}:{int(minute):02d} UTC"
    except ValueError:
        return expr


def _on_block(data: dict[str, Any]) -> dict[str, Any]:
    # PyYAML parses the bare `on:` key as the boolean True.
    raw = data.get(True, data.get("on"))
    return raw if isinstance(raw, dict) else {}


def _parse_inputs(workflow_dispatch: Any) -> list[dict[str, Any]]:
    if not isinstance(workflow_dispatch, dict):
        return []
    inputs = workflow_dispatch.get("inputs")
    if not isinstance(inputs, dict):
        return []
    out: list[dict[str, Any]] = []
    for name, spec in inputs.items():
        spec = spec or {}
        default = spec.get("default")
        options = spec.get("options")
        if isinstance(default, bool):
            default_str: str | None = "true" if default else "false"
        elif default is None:
            default_str = None
        else:
            default_str = str(default)
        out.append(
            {
                "name": name,
                "description": str(spec.get("description", "")),
                "required": bool(spec.get("required", False)),
                "type": str(spec.get("type", "string")),
                "default": default_str,
                "options": [str(o) for o in options] if isinstance(options, list) else None,
            }
        )
    return out


def _flatten_permissions(perms: Any) -> str | None:
    if isinstance(perms, str):
        return perms
    if isinstance(perms, dict):
        return ", ".join(f"{k}: {v}" for k, v in perms.items())
    return None


def _job_facts(data: dict[str, Any]) -> tuple[int | None, str | None]:
    """Max job timeout-minutes and merged (top-level + job) permissions."""
    jobs = data.get("jobs")
    timeouts: list[int] = []
    merged: dict[str, Any] = {}
    top = data.get("permissions")
    if isinstance(top, dict):
        merged.update(top)
    elif isinstance(top, str):
        return _job_max_timeout(jobs), top
    if isinstance(jobs, dict):
        for job in jobs.values():
            if not isinstance(job, dict):
                continue
            t = job.get("timeout-minutes")
            if isinstance(t, int):
                timeouts.append(t)
            jp = job.get("permissions")
            if isinstance(jp, dict):
                merged.update(jp)
    return (max(timeouts) if timeouts else None), _flatten_permissions(merged or None)


def _job_max_timeout(jobs: Any) -> int | None:
    if not isinstance(jobs, dict):
        return None
    timeouts = [
        j["timeout-minutes"]
        for j in jobs.values()
        if isinstance(j, dict) and isinstance(j.get("timeout-minutes"), int)
    ]
    return max(timeouts) if timeouts else None


def _trigger_paths(on: dict[str, Any]) -> list[str] | None:
    paths: list[str] = []
    for key in ("push", "pull_request"):
        spec = on.get(key)
        if isinstance(spec, dict) and isinstance(spec.get("paths"), list):
            paths.extend(str(p) for p in spec["paths"])
    seen = sorted(set(paths))
    return seen or None


def _parse_workflow(path: Path, slug: str) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    data = yaml.safe_load(text) or {}
    on = _on_block(data)

    schedule = on.get("schedule")
    schedules: list[dict[str, str]] = []
    if isinstance(schedule, list):
        for entry in schedule:
            cron = (entry or {}).get("cron") if isinstance(entry, dict) else None
            if cron:
                schedules.append({"cron": str(cron), "human": _describe_cron(str(cron))})

    timeout, permissions = _job_facts(data)
    concurrency = data.get("concurrency")
    group = concurrency.get("group") if isinstance(concurrency, dict) else None
    cancel = (
        concurrency.get("cancel-in-progress")
        if isinstance(concurrency, dict)
        else None
    )

    secrets = sorted(set(re.findall(r"secrets\.([A-Za-z0-9_]+)", text)))

    return {
        "filename": path.name,
        "name": str(data.get("name", path.name)),
        "description": _leading_description(text),
        "manual": "workflow_dispatch" in on,
        "schedules": schedules,
        "onPush": "push" in on,
        "onPullRequest": "pull_request" in on,
        "paths": _trigger_paths(on),
        "inputs": _parse_inputs(on.get("workflow_dispatch")),
        "secrets": secrets,
        "concurrencyGroup": str(group) if group else None,
        "cancelInProgress": bool(cancel) if isinstance(cancel, bool) else None,
        "timeoutMinutes": timeout,
        "permissions": permissions,
        "runsUrl": f"https://github.com/{slug}/actions/workflows/{path.name}",
        "sourceUrl": (
            f"https://github.com/{slug}/blob/{DEFAULT_BRANCH}/.github/workflows/{path.name}"
        ),
    }


def generate() -> str:
    root = Path(__file__).resolve().parent.parent
    slug = _repo_slug()
    workflows_dir = root / ".github" / "workflows"
    files = sorted(workflows_dir.glob("*.yml"))
    docs = [_parse_workflow(p, slug) for p in files]
    body = json.dumps(docs, indent=2, ensure_ascii=False)
    payload = f"export const WORKFLOW_DOCS: WorkflowDoc[] = {body};\n"
    return "\n".join([HEADER, TS_TYPES, payload])


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit frontend/src/lib/workflowDocs.generated.ts",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Exit non-zero if the on-disk file differs from the freshly "
            "generated content. For CI drift detection."
        ),
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    out_path = root / "frontend" / "src" / "lib" / "workflowDocs.generated.ts"
    content = generate()

    if args.check:
        if not out_path.exists():
            print(
                f"::error::{out_path} is missing; "
                f"run `python scripts/generate_workflow_docs.py` "
                f"and commit the result.",
                file=sys.stderr,
            )
            return 1
        if out_path.read_text(encoding="utf-8") != content:
            print(
                f"::error::{out_path} is stale; "
                f"run `python scripts/generate_workflow_docs.py` "
                f"and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {out_path} matches the workflow YAML.")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
