"""Emit `frontend/src/lib/filterRegistry.generated.ts` from the Python registry.

Single source of truth: `toolkit/filter_registry.py`. This script
reads the in-memory registry and writes a typed TypeScript file the
frontend imports for:

- `<FilterForm>` widget dispatch (uses `ui_control`),
- URL serialisation in `lib/filters.ts` (uses `id` + `type`),
- enum option labels (Czech + English),
- the Settings page's agenda × filter matrix.

Run modes:

- `python scripts/generate_filter_registry.py`  — emit the file.
- `python scripts/generate_filter_registry.py --check` — exit non-zero
  if the on-disk file differs from what we'd generate. Wired into CI
  so a registry edit without a regen fails the build.

The output is committed to the repo so Vite doesn't need to invoke
Python at build time. CI is the drift guard.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from toolkit import filter_registry as fr


HEADER = """\
// AUTOGENERATED — DO NOT EDIT.
// Source of truth: toolkit/filter_registry.py.
// Regenerate with: python scripts/generate_filter_registry.py
//
// CI runs `--check` and fails on drift, so any registry edit must
// be paired with a fresh regen in the same commit. The shape mirrors
// the JSON served by `GET /admin/filter-schema` so runtime fetches
// and the codegen are interchangeable.
"""


TS_TYPES = """\
export type Agenda =
{agenda_union}

export type UiControl =
{ui_control_union}

export type FilterType =
{filter_type_union}

export interface EnumOption {{
  value: string | number;
  label_cs: string;
  label_en: string;
  group?: string;
}}

export interface FilterDef {{
  id: string;
  type: FilterType;
  pg_column: string | null;
  default: unknown;
  description: string;
  category: string;
  ui_control: UiControl;
  agendas: Agenda[];
  constraints: Record<string, unknown> | null;
  unit: string | null;
  enum_values: EnumOption[] | null;
  aliases: string[];
}}

export interface FilterRegistryPayload {{
  agendas: Agenda[];
  categories: string[];
  ui_controls: UiControl[];
  filters: FilterDef[];
}}
"""


def _ts_union(values: list[str]) -> str:
    return "\n".join(f'  | "{v}"' for v in values) + ";"


def _render_payload(payload: dict[str, Any]) -> str:
    # Strip the per-filter `visibility` map — the static codegen
    # captures the registry-declared agendas only; visibility comes
    # from the runtime endpoint.
    sanitised = {
        **payload,
        "filters": [
            {k: v for k, v in f.items() if k != "visibility"}
            for f in payload["filters"]
        ],
    }
    body = json.dumps(sanitised, indent=2, ensure_ascii=False)
    return f"export const FILTER_REGISTRY: FilterRegistryPayload = {body};\n"


def _render_helpers() -> str:
    return """\
export function filterById(id: string): FilterDef | undefined {
  return FILTER_REGISTRY.filters.find((f) => f.id === id);
}

export function filtersForAgenda(agenda: Agenda): FilterDef[] {
  return FILTER_REGISTRY.filters.filter((f) => f.agendas.includes(agenda));
}

export const AGENDAS = FILTER_REGISTRY.agendas;
export const CATEGORIES = FILTER_REGISTRY.categories;
export const UI_CONTROLS = FILTER_REGISTRY.ui_controls;
"""


def _render_constants() -> str:
    # Canonical enum tuples emitted from the registry so the frontend's
    # `__unknown__`-sentinel logic (queries.ts enumOrUnknown) reads the SAME
    # values as the SQL RPC / Watchdog / toolkit — one source, no hand-coded
    # duplicate that can silently drift (architectural rule #16).
    def _arr(name: str, values: tuple[str, ...]) -> str:
        items = ", ".join(f'"{v}"' for v in values)
        return f"export const {name} = [{items}] as const;"

    return "\n".join(
        [
            "/* Canonical enum values — single source for the `__unknown__`-sentinel",
            " * multi-select logic (a value that also matches NULL / non-canonical).",
            " * Generated from toolkit.filter_registry; do not hand-edit. */",
            _arr("FURNISHED_CANONICAL", fr.FURNISHED_CANONICAL),
            _arr("OWNERSHIP_CANONICAL", fr.OWNERSHIP_CANONICAL),
            "",
        ]
    )


def generate() -> str:
    payload = fr.registry_to_json(visibility=None)
    types = TS_TYPES.format(
        agenda_union=_ts_union(payload["agendas"]),
        ui_control_union=_ts_union(payload["ui_controls"]),
        filter_type_union=_ts_union(
            sorted({f["type"] for f in payload["filters"]})
        ),
    )
    return "\n".join(
        [
            HEADER,
            types,
            _render_payload(payload),
            _render_helpers(),
            _render_constants(),
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit frontend/src/lib/filterRegistry.generated.ts",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Exit non-zero if the on-disk file differs from the "
            "freshly generated content. For CI drift detection."
        ),
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    out_path = root / "frontend" / "src" / "lib" / "filterRegistry.generated.ts"
    content = generate()

    if args.check:
        if not out_path.exists():
            print(
                f"::error::{out_path} is missing; "
                f"run `python scripts/generate_filter_registry.py` "
                f"and commit the result.",
                file=sys.stderr,
            )
            return 1
        existing = out_path.read_text(encoding="utf-8")
        if existing != content:
            print(
                f"::error::{out_path} is stale; "
                f"run `python scripts/generate_filter_registry.py` "
                f"and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {out_path} matches the registry.")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
