"""Regenerate the auto-status block at the top of ROADMAP.md.

Wired in by `.claude/settings.json` as a SessionStart hook. The block
between `<!-- BEGIN AUTO-STATUS -->` and `<!-- END AUTO-STATUS -->` is
overwritten on every run; everything outside the markers is left alone.

Designed to never block a session start: any failure (DB unreachable,
git binary missing, malformed marker block) is logged to stderr and the
script exits zero with a "could not refresh" placeholder.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROADMAP = REPO_ROOT / "ROADMAP.md"
MIGRATIONS_DIR = REPO_ROOT / "migrations"
BEGIN = "<!-- BEGIN AUTO-STATUS - regenerated by scripts/regenerate_roadmap_status.py -->"
END = "<!-- END AUTO-STATUS -->"
BLOCK_PATTERN = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END), flags=re.DOTALL
)


def _git(*args: str) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        print(f"git {args[0]} failed: {exc}", file=sys.stderr)
        return ""


def _gather_db_facts() -> dict[str, object] | None:
    dsn = os.environ.get("SUPABASE_DB_URL")
    if not dsn:
        return None
    try:
        import psycopg  # type: ignore
    except ImportError:
        print("psycopg not installed; skipping DB facts", file=sys.stderr)
        return None

    try:
        with psycopg.connect(dsn, prepare_threshold=None, connect_timeout=5) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT count(*),"
                    " count(*) filter (where is_active"
                    "                  and last_seen_at > now() - interval '7 days')"
                    " FROM listings"
                )
                total_listings, active_listings = cur.fetchone()

                cur.execute(
                    "SELECT category_main, category_type, count(*)"
                    " FROM listings"
                    " WHERE is_active and last_seen_at > now() - interval '7 days'"
                    " GROUP BY 1, 2"
                    " ORDER BY 1, 2"
                )
                category_breakdown = cur.fetchall()

                cur.execute("SELECT count(*) FROM listing_snapshots")
                (total_snapshots,) = cur.fetchone()

                cur.execute("SELECT max(scraped_at) FROM listings")
                (last_scrape,) = cur.fetchone()

                cur.execute(
                    "SELECT status, count(*)"
                    " FROM estimation_runs"
                    " WHERE created_at > now() - interval '30 days'"
                    " GROUP BY 1"
                    " ORDER BY 1"
                )
                estimations_30d = cur.fetchall()

                cur.execute(
                    "SELECT coalesce(sum(cost_usd), 0)::float"
                    " FROM llm_calls"
                    " WHERE called_at >= date_trunc('month', now())"
                )
                (llm_cost_mtd,) = cur.fetchone()

                cur.execute(
                    "SELECT count(*) FROM listing_fetch_failures WHERE given_up = true"
                )
                (given_up,) = cur.fetchone()

        return {
            "total_listings": total_listings,
            "active_listings": active_listings,
            "category_breakdown": category_breakdown,
            "total_snapshots": total_snapshots,
            "last_scrape": last_scrape,
            "estimations_30d": estimations_30d,
            "llm_cost_mtd": llm_cost_mtd,
            "given_up": given_up,
        }
    except Exception as exc:  # noqa: BLE001
        print(f"DB query failed: {exc}", file=sys.stderr)
        return None


def _format_scrape_recency(last_scrape: datetime | None) -> str:
    if last_scrape is None:
        return "never"
    if last_scrape.tzinfo is None:
        last_scrape = last_scrape.replace(tzinfo=timezone.utc)
    delta = datetime.now(timezone.utc) - last_scrape
    hours = int(delta.total_seconds() // 3600)
    iso = last_scrape.strftime("%Y-%m-%d %H:%M UTC")
    flag = " **(stale, > 36 h)**" if hours > 36 else ""
    return f"{iso} ({hours} h ago){flag}"


def _render_block(db_facts: dict[str, object] | None) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        BEGIN,
        "<!-- This block is overwritten at the start of every Claude Code session.",
        "     Do not hand-edit; changes will be lost. The narrative phase entries",
        "     live in roadmap/<track>.md per the Tracks index below. -->",
        "",
        f"_Last refreshed: {now}_",
        "",
    ]

    branch = _git("rev-parse", "--abbrev-ref", "HEAD") or "(unknown)"
    lines.append(f"**Branch:** `{branch}`")
    lines.append("")

    if db_facts is None:
        lines.append(
            "**Database:** unavailable this session "
            "(`SUPABASE_DB_URL` not set or unreachable)."
        )
        lines.append("")
    else:
        lines.append("**Database:**")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| Total listings | {db_facts['total_listings']:,} |")
        lines.append(
            f"| Active (seen ≤ 7 d) | {db_facts['active_listings']:,} |"
        )
        lines.append(f"| Total snapshots | {db_facts['total_snapshots']:,} |")
        lines.append(
            f"| Last scrape | {_format_scrape_recency(db_facts['last_scrape'])} |"
        )
        lines.append(f"| Given-up fetch failures | {db_facts['given_up']:,} |")
        lines.append(
            f"| LLM cost MTD | ${db_facts['llm_cost_mtd']:.2f} |"
        )
        lines.append("")
        breakdown = db_facts["category_breakdown"]
        if breakdown:
            lines.append("**Active listings by category (seen ≤ 7 d):**")
            lines.append("")
            lines.append("| category_main | category_type | count |")
            lines.append("|---|---|---|")
            for main, kind, count in breakdown:
                lines.append(f"| {main} | {kind} | {count:,} |")
            lines.append("")
        runs = db_facts["estimations_30d"]
        if runs:
            lines.append("**Estimation runs (last 30 d):**")
            lines.append("")
            for status, count in runs:
                lines.append(f"- `{status}`: {count:,}")
            lines.append("")
        else:
            lines.append("**Estimation runs (last 30 d):** none.")
            lines.append("")

    if MIGRATIONS_DIR.is_dir():
        files = sorted(p.name for p in MIGRATIONS_DIR.glob("*.sql"))
        if files:
            highest = files[-1]
            lines.append(
                f"**Migrations on disk:** {len(files)} files, latest `{highest}`."
            )
            lines.append("")

    log = _git("log", "--oneline", "-10")
    if log:
        lines.append("**Last 10 commits:**")
        lines.append("")
        lines.append("```")
        lines.append(log)
        lines.append("```")
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    if not ROADMAP.is_file():
        print(f"ROADMAP.md not found at {ROADMAP}", file=sys.stderr)
        return 0

    original = ROADMAP.read_text(encoding="utf-8")
    db_facts = _gather_db_facts()
    new_block = _render_block(db_facts)

    if BLOCK_PATTERN.search(original):
        updated = BLOCK_PATTERN.sub(new_block, original, count=1)
    else:
        m = re.search(r"^# .*?\n", original, flags=re.MULTILINE)
        if m:
            insert_at = m.end()
            updated = (
                original[:insert_at] + "\n" + new_block + "\n\n" + original[insert_at:]
            )
        else:
            updated = new_block + "\n\n" + original

    if updated != original:
        tmp = ROADMAP.with_suffix(".md.tmp")
        tmp.write_text(updated, encoding="utf-8")
        tmp.replace(ROADMAP)
    return 0


if __name__ == "__main__":
    sys.exit(main())
