// AUTOGENERATED — DO NOT EDIT.
// Source of truth: toolkit/filter_registry.py.
// Regenerate with: python scripts/generate_filter_registry.py
//
// CI runs `--check` and fails on drift, so any registry edit must
// be paired with a fresh regen in the same commit. The shape mirrors
// the JSON served by `GET /admin/filter-schema` so runtime fetches
// and the codegen are interchangeable.

export type Agenda =
  | "browse"
  | "watchdog"
  | "comparables"
  | "estimation"
  | "velocity"
  | "neighborhood"
  | "defaults";

export type UiControl =
  | "range_slider"
  | "range_inputs"
  | "pill_group"
  | "multiselect"
  | "tristate"
  | "single_select"
  | "number_input"
  | "csv_input"
  | "boolean"
  | "location"
  | "city_index_rules"
  | "near_city_rule";

export type FilterType =
  | "bool"
  | "city_index_rule_list"
  | "district_chip_list"
  | "float"
  | "int"
  | "int_list"
  | "location"
  | "near_city_proximity"
  | "string"
  | "string_list";

export interface EnumOption {
  value: string | number;
  label_cs: string;
  label_en: string;
}

export interface FilterDef {
  id: string;
  type: FilterType;
  pg_column: string | null;
  default: unknown;
  description: string;
  category: string;
  ui_control: UiControl;
  agendas: Agenda[];
  constraints: Record<string, unknown> | null;
  unit: string | null;
  enum_values: EnumOption[] | null;
  aliases: string[];
}

export interface FilterRegistryPayload {
  agendas: Agenda[];
  categories: string[];
  ui_controls: UiControl[];
  filters: FilterDef[];
}

export const FILTER_REGISTRY: FilterRegistryPayload = {
  "agendas": [
    "browse",
    "watchdog",
    "comparables",
    "estimation",
    "velocity",
    "neighborhood",
    "defaults"
  ],
  "categories": [
    "Spatial",
    "Property",
    "Amenity",
    "Velocity",
    "Status",
    "Curation",
    "Cohort tuning"
  ],
  "ui_controls": [
    "range_slider",
    "range_inputs",
    "pill_group",
    "multiselect",
    "tristate",
    "single_select",
    "number_input",
    "csv_input",
    "boolean",
    "location",
    "city_index_rules",
    "near_city_rule"
  ],
  "filters": [
    {
      "id": "location",
      "type": "location",
      "pg_column": null,
      "default": null,
      "description": "Where the listing must be. Composite filter with three complementary sub-fields: a district name list (matched against l.district), a map bounding box (west/south/east/north on l.geom), and a center+radius pair (ST_DWithin around (lat,lng) within radius_m). Districts is an independent AND-clause; the map vs center+radius pair are mutually exclusive — when both are set, center+radius wins. Leave everything null for no spatial restriction.",
      "category": "Spatial",
      "ui_control": "location",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "districts",
      "type": "district_chip_list",
      "pg_column": "district",
      "default": null,
      "description": "Match listings whose `district` (human-readable text) is in the list. Each chip is an object `{name: str, context: str | null}`: `name` is the primary phrase to match (ILIKE substring across `district` and `locality`), `context` is the parent municipality from Mapy.cz's `regionalStructure` that narrows the match when set (so picking the Plzeň entry for 'Edvarda Beneše' doesn't drag in the Olomouc + Hradec Králové streets of the same name). Multi-value AND-of-OR: a listing matches if ANY chip matches, and districts is AND'd with the other filters. Use `locality_district_id` for renames-stable matching.",
      "category": "Spatial",
      "ui_control": "multiselect",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "radius_m",
      "type": "int",
      "pg_column": null,
      "default": 1000,
      "description": "Spatial radius around the target listing, in metres. Applied as ST_DWithin(l.geom, target_point, radius_m). Defaults to 1000 m — a tight 10-minute walk. Widen for sparse rural cohorts; tighten for dense urban blocks where a few hundred metres changes the price level materially.",
      "category": "Cohort tuning",
      "ui_control": "number_input",
      "agendas": [
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity"
      ],
      "constraints": {
        "min": 100,
        "max": 10000
      },
      "unit": "m",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "area_band_pct",
      "type": "float",
      "pg_column": null,
      "default": 0.2,
      "description": "Half-width of the area band around the target's area_m2, expressed as a fraction. 0.20 means ±20% — a 60 m² target accepts comparables in 48 m² – 72 m². Widen on small cohorts; tighten when the cohort is large enough to demand a closer match.",
      "category": "Cohort tuning",
      "ui_control": "number_input",
      "agendas": [
        "comparables",
        "defaults",
        "estimation",
        "velocity"
      ],
      "constraints": {
        "min": 0.05,
        "max": 0.6,
        "step": 0.05
      },
      "unit": "%",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "disposition_match",
      "type": "string",
      "pg_column": null,
      "default": "exact",
      "description": "How strictly the cohort's disposition must match the target's. `exact` requires the same string (e.g. 3+kk = 3+kk). `loose` collapses kk-vs-1 pairs (3+kk ↔ 3+1). `any` drops the constraint.",
      "category": "Cohort tuning",
      "ui_control": "single_select",
      "agendas": [
        "comparables",
        "defaults",
        "estimation",
        "velocity"
      ],
      "constraints": {
        "enum": [
          "exact",
          "loose",
          "any"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "exact",
          "label_cs": "Přesně",
          "label_en": "Exact"
        },
        {
          "value": "loose",
          "label_cs": "Volně",
          "label_en": "Loose (kk ↔ 1)"
        },
        {
          "value": "any",
          "label_cs": "Libovolně",
          "label_en": "Any"
        }
      ],
      "aliases": []
    },
    {
      "id": "floor_band",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "If set, restrict the cohort to listings whose `floor` is within ±N of the target's floor. Omit (the default) to ignore floor entirely. Useful in apartment buildings where ground-floor and top-floor prices diverge from the middle floors.",
      "category": "Cohort tuning",
      "ui_control": "number_input",
      "agendas": [
        "comparables",
        "estimation",
        "velocity"
      ],
      "constraints": {
        "min": 0,
        "max": 20
      },
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "max_age_days",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "Drop listings whose `last_seen_at` is older than N days. Applied only when `population` resolves to `active` (or `active_only=true`). Set explicitly when you want a freshness gate — there's no implicit default.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity"
      ],
      "constraints": {
        "min": 1,
        "max": 365
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "active_only",
      "type": "bool",
      "pg_column": null,
      "default": false,
      "description": "When true, restricts the cohort to `l.is_active = true`. Legacy boolean retained for backwards compatibility; `population='active'` is the modern equivalent and carries the same effect plus an optional freshness gate via `max_age_days`.",
      "category": "Status",
      "ui_control": "boolean",
      "agendas": [
        "comparables",
        "defaults",
        "estimation"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": [
        "activeOnly"
      ]
    },
    {
      "id": "population",
      "type": "string",
      "pg_column": null,
      "default": null,
      "description": "Coarse cohort population selector. `active` = is_active=true (plus max_age_days if set); `delisted` = is_active=false (closed deals only — rough proxy for transacted listings); `all` = both. Mutually exclusive with `active_only`; if both are set, population wins.",
      "category": "Status",
      "ui_control": "single_select",
      "agendas": [
        "comparables",
        "estimation",
        "velocity"
      ],
      "constraints": {
        "enum": [
          "active",
          "delisted",
          "all"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "active",
          "label_cs": "Aktivní",
          "label_en": "Active"
        },
        {
          "value": "delisted",
          "label_cs": "Stažené",
          "label_en": "Delisted"
        },
        {
          "value": "all",
          "label_cs": "Vše",
          "label_en": "All"
        }
      ],
      "aliases": []
    },
    {
      "id": "status",
      "type": "string",
      "pg_column": null,
      "default": "any",
      "description": "Listing status filter for Browse. `any` shows both live and delisted; `active` only is_active=true; `inactive` only is_active=false. The Watchdog matcher ignores this (it fires on new listings only) — use `population` for the analytical surfaces.",
      "category": "Status",
      "ui_control": "pill_group",
      "agendas": [
        "browse"
      ],
      "constraints": {
        "enum": [
          "any",
          "active",
          "inactive"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "any",
          "label_cs": "Vše",
          "label_en": "Any"
        },
        {
          "value": "active",
          "label_cs": "Aktivní",
          "label_en": "Active"
        },
        {
          "value": "inactive",
          "label_cs": "Neaktivní",
          "label_en": "Inactive"
        }
      ],
      "aliases": []
    },
    {
      "id": "tom_days_min",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "Lower bound on time-on-market in days. TOM = (now - first_seen_at) for active rows, (last_seen_at - first_seen_at) for delisted rows. Inclusive.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "estimation"
      ],
      "constraints": {
        "min": 0
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "tom_days_max",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "Upper bound on time-on-market in days. See `tom_days_min` for the TOM definition. Inclusive.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "estimation"
      ],
      "constraints": {
        "min": 0
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "last_seen_min_days",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "`last_seen_at <= now() - N days`. Days-ago floor — set N=3 to exclude listings seen in the last 2 days. Pair with `last_seen_max_days` for a window.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "estimation"
      ],
      "constraints": {
        "min": 0
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "last_seen_max_days",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "`last_seen_at >= now() - N days`. Days-ago ceiling — set N=30 to exclude listings not seen in the last 30 days. Pair with `last_seen_min_days` for a window.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "estimation"
      ],
      "constraints": {
        "min": 0
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "first_seen_min_days",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "`first_seen_at <= now() - N days`. Excludes listings that first appeared in the last N days. Useful for filtering out brand-new postings when looking at established cohorts.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "estimation"
      ],
      "constraints": {
        "min": 0
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "first_seen_max_days",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "`first_seen_at >= now() - N days`. Restricts to listings first seen in the last N days. The classic 'show me new listings' filter.",
      "category": "Velocity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "estimation"
      ],
      "constraints": {
        "min": 0
      },
      "unit": "days",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "category_main",
      "type": "string",
      "pg_column": "category_main",
      "default": "byt",
      "description": "Top-level sreality category. `byt` = apartments, `dum` = houses, `komercni` = commercial. `pozemek` (land) and `ostatni` (other) exist in the data but the app's downstream surfaces target the first three.",
      "category": "Property",
      "ui_control": "pill_group",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "enum": [
          "byt",
          "dum",
          "komercni",
          "pozemek",
          "ostatni"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "byt",
          "label_cs": "Byty",
          "label_en": "Apartments"
        },
        {
          "value": "dum",
          "label_cs": "Domy",
          "label_en": "Houses"
        },
        {
          "value": "komercni",
          "label_cs": "Komerční",
          "label_en": "Commercial"
        },
        {
          "value": "pozemek",
          "label_cs": "Pozemky",
          "label_en": "Land"
        },
        {
          "value": "ostatni",
          "label_cs": "Ostatní",
          "label_en": "Other"
        }
      ],
      "aliases": []
    },
    {
      "id": "category_type",
      "type": "string",
      "pg_column": "category_type",
      "default": "pronajem",
      "description": "Deal type. `pronajem` = for rent, `prodej` = for sale, `drazba` = auction, `podil` = fractional ownership. Default depends on context: estimation flows use the estimate_kind to pick (rent → pronajem, sale → prodej).",
      "category": "Property",
      "ui_control": "pill_group",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "enum": [
          "pronajem",
          "prodej",
          "drazba",
          "podil"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "pronajem",
          "label_cs": "Pronájem",
          "label_en": "For rent"
        },
        {
          "value": "prodej",
          "label_cs": "Prodej",
          "label_en": "For sale"
        },
        {
          "value": "drazba",
          "label_cs": "Dražba",
          "label_en": "Auction"
        },
        {
          "value": "podil",
          "label_cs": "Podíl",
          "label_en": "Fractional"
        }
      ],
      "aliases": []
    },
    {
      "id": "category_sub_cb",
      "type": "int",
      "pg_column": "category_sub_cb",
      "default": null,
      "description": "Numeric sreality sub-category code (e.g. 6 = 3+kk, 37 = rodinný dům). Narrows the cohort aggressively — use sparingly. The frontend renders this as a dropdown keyed by category_main.",
      "category": "Property",
      "ui_control": "single_select",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "dispositions",
      "type": "string_list",
      "pg_column": "disposition",
      "default": null,
      "description": "Multi-select disposition list (1+kk, 1+1, 2+kk, …). A listing matches if its disposition is in the list. Empty list / null = no constraint. Used by Browse + Watchdog UI; the analytical surfaces use `disposition_match` together with the target's disposition instead.",
      "category": "Property",
      "ui_control": "multiselect",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": [
        {
          "value": "1+kk",
          "label_cs": "1+kk",
          "label_en": "1+kk"
        },
        {
          "value": "1+1",
          "label_cs": "1+1",
          "label_en": "1+1"
        },
        {
          "value": "2+kk",
          "label_cs": "2+kk",
          "label_en": "2+kk"
        },
        {
          "value": "2+1",
          "label_cs": "2+1",
          "label_en": "2+1"
        },
        {
          "value": "3+kk",
          "label_cs": "3+kk",
          "label_en": "3+kk"
        },
        {
          "value": "3+1",
          "label_cs": "3+1",
          "label_en": "3+1"
        },
        {
          "value": "4+kk",
          "label_cs": "4+kk",
          "label_en": "4+kk"
        },
        {
          "value": "4+1",
          "label_cs": "4+1",
          "label_en": "4+1"
        },
        {
          "value": "5+kk",
          "label_cs": "5+kk",
          "label_en": "5+kk"
        },
        {
          "value": "5+1",
          "label_cs": "5+1",
          "label_en": "5+1"
        }
      ],
      "aliases": []
    },
    {
      "id": "condition_match",
      "type": "string_list",
      "pg_column": "condition",
      "default": null,
      "description": "Restrict cohort to listings whose `condition` is in this list. Czech values without diacritics: novostavba, po_rekonstrukci, velmi_dobry, dobry, pred_rekonstrukci, k_demolici.",
      "category": "Property",
      "ui_control": "multiselect",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": [
        {
          "value": "novostavba",
          "label_cs": "Novostavba",
          "label_en": "New build"
        },
        {
          "value": "po_rekonstrukci",
          "label_cs": "Po rekonstrukci",
          "label_en": "Recently renovated"
        },
        {
          "value": "velmi_dobry",
          "label_cs": "Velmi dobrý",
          "label_en": "Very good"
        },
        {
          "value": "dobry",
          "label_cs": "Dobrý",
          "label_en": "Good"
        },
        {
          "value": "pred_rekonstrukci",
          "label_cs": "Před rekonstrukcí",
          "label_en": "Needs renovation"
        },
        {
          "value": "k_demolici",
          "label_cs": "K demolici",
          "label_en": "For demolition"
        }
      ],
      "aliases": []
    },
    {
      "id": "building_type_match",
      "type": "string_list",
      "pg_column": "building_type",
      "default": null,
      "description": "Restrict cohort to listings whose `building_type` is in this list. Czech values: cihla, panel, smisena, skelet, drevo, kamen, montovana, nizkoenergeticka.",
      "category": "Property",
      "ui_control": "multiselect",
      "agendas": [
        "comparables",
        "estimation",
        "velocity"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": [
        {
          "value": "cihla",
          "label_cs": "Cihla",
          "label_en": "Brick"
        },
        {
          "value": "panel",
          "label_cs": "Panel",
          "label_en": "Panel"
        },
        {
          "value": "smisena",
          "label_cs": "Smíšená",
          "label_en": "Mixed"
        },
        {
          "value": "skelet",
          "label_cs": "Skelet",
          "label_en": "Skeleton"
        },
        {
          "value": "drevo",
          "label_cs": "Dřevěná",
          "label_en": "Wood"
        },
        {
          "value": "kamen",
          "label_cs": "Kamenná",
          "label_en": "Stone"
        },
        {
          "value": "montovana",
          "label_cs": "Montovaná",
          "label_en": "Prefab"
        },
        {
          "value": "nizkoenergeticka",
          "label_cs": "Nízkoenergetická",
          "label_en": "Low-energy"
        }
      ],
      "aliases": []
    },
    {
      "id": "building_material",
      "type": "string",
      "pg_column": "building_type",
      "default": null,
      "description": "Operator-friendly building material bucket. The four values (cihla / panel / smisena / ostatni) map onto the granular building_type column; `ostatni` expands to skelet / drevo / kamen / montovana / nizkoenergeticka under the hood.",
      "category": "Property",
      "ui_control": "single_select",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": {
        "enum": [
          "cihla",
          "panel",
          "smisena",
          "ostatni"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "cihla",
          "label_cs": "Cihla",
          "label_en": "Brick"
        },
        {
          "value": "panel",
          "label_cs": "Panel",
          "label_en": "Panel"
        },
        {
          "value": "smisena",
          "label_cs": "Smíšená",
          "label_en": "Mixed"
        },
        {
          "value": "ostatni",
          "label_cs": "Ostatní",
          "label_en": "Other"
        }
      ],
      "aliases": []
    },
    {
      "id": "energy_rating_match",
      "type": "string_list",
      "pg_column": "energy_rating",
      "default": null,
      "description": "Restrict to energy ratings in this list (single capital letters A through G). New constructions trend A/B; pre-renovation panel buildings often G.",
      "category": "Property",
      "ui_control": "multiselect",
      "agendas": [
        "comparables",
        "estimation",
        "velocity"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": [
        {
          "value": "A",
          "label_cs": "A",
          "label_en": "A"
        },
        {
          "value": "B",
          "label_cs": "B",
          "label_en": "B"
        },
        {
          "value": "C",
          "label_cs": "C",
          "label_en": "C"
        },
        {
          "value": "D",
          "label_cs": "D",
          "label_en": "D"
        },
        {
          "value": "E",
          "label_cs": "E",
          "label_en": "E"
        },
        {
          "value": "F",
          "label_cs": "F",
          "label_en": "F"
        },
        {
          "value": "G",
          "label_cs": "G",
          "label_en": "G"
        }
      ],
      "aliases": []
    },
    {
      "id": "building_condition_level_min",
      "type": "int",
      "pg_column": "building_condition_level",
      "default": null,
      "description": "Minimum building condition score (`building_condition_level >= N`, 1..5). Set by toolkit.condition_scoring.score_listing_condition off the curated Czech marker dictionary + 5-level rubric. NULL rows (not yet scored) are excluded from the result. 5 = výborný stav (excellent), 4 = velmi dobrý stav, 3 = průměrný / udržovaný, 2 = vyžaduje rekonstrukci, 1 = kritický stav.",
      "category": "Property",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 1,
        "max": 5
      },
      "unit": null,
      "enum_values": null,
      "aliases": [
        "buildingConditionLevelMin"
      ]
    },
    {
      "id": "apartment_condition_level_min",
      "type": "int",
      "pg_column": "apartment_condition_level",
      "default": null,
      "description": "Minimum apartment condition score (`apartment_condition_level >= N`, 1..5). Same scorer as building_condition_level_min but scoped to the unit itself rather than the building shell. NULL rows (not yet scored) are excluded from the result. 5 = výborný stav (novostavba / po kompletní rekonstrukci), 4 = velmi dobrý stav (po rekonstrukci, new jádro / koupelna), 3 = průměrný, 2 = v původním stavu / před rekonstrukcí, 1 = umakartové jádro.",
      "category": "Property",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 1,
        "max": 5
      },
      "unit": null,
      "enum_values": null,
      "aliases": [
        "apartmentConditionLevelMin"
      ]
    },
    {
      "id": "furnished",
      "type": "string",
      "pg_column": "furnished",
      "default": null,
      "description": "Furnishing status. `ano` = furnished, `ne` = unfurnished, `castecne` = partially furnished. Null drops the constraint.",
      "category": "Property",
      "ui_control": "single_select",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "enum": [
          "ano",
          "ne",
          "castecne"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "ano",
          "label_cs": "Vybaveno",
          "label_en": "Furnished"
        },
        {
          "value": "ne",
          "label_cs": "Nevybaveno",
          "label_en": "Unfurnished"
        },
        {
          "value": "castecne",
          "label_cs": "Částečně",
          "label_en": "Partially furnished"
        }
      ],
      "aliases": []
    },
    {
      "id": "ownership",
      "type": "string",
      "pg_column": "ownership",
      "default": null,
      "description": "Ownership type. `osobni` = personal (full title), `druzstevni` = cooperative (member share), `statni` = state/municipal. Materially affects sale prices (druzstevni typically 10–20% cheaper than osobni).",
      "category": "Property",
      "ui_control": "single_select",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "enum": [
          "osobni",
          "druzstevni",
          "statni"
        ]
      },
      "unit": null,
      "enum_values": [
        {
          "value": "osobni",
          "label_cs": "Osobní",
          "label_en": "Personal"
        },
        {
          "value": "druzstevni",
          "label_cs": "Družstevní",
          "label_en": "Cooperative"
        },
        {
          "value": "statni",
          "label_cs": "Státní/obecní",
          "label_en": "State/Municipal"
        }
      ],
      "aliases": []
    },
    {
      "id": "has_balcony",
      "type": "bool",
      "pg_column": "has_balcony",
      "default": null,
      "description": "Legacy combined flag: balcony OR terrace OR loggia. Kept for backwards compatibility; prefer the granular `terrace` filter when only a terrace will do.",
      "category": "Amenity",
      "ui_control": "tristate",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": [
        "balcony"
      ]
    },
    {
      "id": "has_lift",
      "type": "bool",
      "pg_column": "has_lift",
      "default": null,
      "description": "Elevator. True / false / null.",
      "category": "Amenity",
      "ui_control": "tristate",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": [
        "lift"
      ]
    },
    {
      "id": "has_parking",
      "type": "bool",
      "pg_column": "has_parking",
      "default": null,
      "description": "Legacy combined flag: any parking (street, lot, or garage). Prefer the granular `garage` and `parking_lots_min` filters for new analytical work.",
      "category": "Amenity",
      "ui_control": "tristate",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": [
        "parking"
      ]
    },
    {
      "id": "terrace",
      "type": "bool",
      "pg_column": "terrace",
      "default": null,
      "description": "Dedicated terrace (not just a balcony).",
      "category": "Amenity",
      "ui_control": "tristate",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "cellar",
      "type": "bool",
      "pg_column": "cellar",
      "default": null,
      "description": "Cellar / basement storage.",
      "category": "Amenity",
      "ui_control": "tristate",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "garage",
      "type": "bool",
      "pg_column": "garage",
      "default": null,
      "description": "Enclosed garage (distinct from open parking lot).",
      "category": "Amenity",
      "ui_control": "tristate",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "min_parking_lots",
      "type": "int",
      "pg_column": "parking_lots",
      "default": null,
      "description": "Minimum number of parking spaces (`parking_lots >= N`). Includes open lots, covered, and garages; for an enclosed-garage-only constraint use `garage=true`.",
      "category": "Amenity",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0
      },
      "unit": null,
      "enum_values": null,
      "aliases": [
        "parking_lots_min",
        "parkingLotsMin"
      ]
    },
    {
      "id": "min_price_czk",
      "type": "int",
      "pg_column": "price_czk",
      "default": null,
      "description": "Lower bound on listing price in CZK. For rentals this is the monthly rent; for sales the total asking price. Inclusive.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 100000,
        "step": 500
      },
      "unit": "CZK",
      "enum_values": null,
      "aliases": [
        "price_min",
        "priceMin"
      ]
    },
    {
      "id": "max_price_czk",
      "type": "int",
      "pg_column": "price_czk",
      "default": null,
      "description": "Upper bound on listing price in CZK. See `min_price_czk` for the rental-vs-sale semantics. Inclusive.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 100000,
        "step": 500
      },
      "unit": "CZK",
      "enum_values": null,
      "aliases": [
        "price_max",
        "priceMax"
      ]
    },
    {
      "id": "min_price_per_m2",
      "type": "float",
      "pg_column": "price_per_m2",
      "default": null,
      "description": "Lower bound on price per square metre (`price_czk / area_m2`). Inclusive. Listings with NULL area_m2 fall out when this bound is set. Useful for sale filtering where absolute price varies wildly with size but unit price is the comparable metric.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 500000,
        "step": 1000
      },
      "unit": "CZK/m²",
      "enum_values": null,
      "aliases": [
        "price_per_m2_min",
        "pricePerM2Min"
      ]
    },
    {
      "id": "max_price_per_m2",
      "type": "float",
      "pg_column": "price_per_m2",
      "default": null,
      "description": "Upper bound on price per square metre. See `min_price_per_m2`. Inclusive.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 500000,
        "step": 1000
      },
      "unit": "CZK/m²",
      "enum_values": null,
      "aliases": [
        "price_per_m2_max",
        "pricePerM2Max"
      ]
    },
    {
      "id": "min_area_m2",
      "type": "float",
      "pg_column": "area_m2",
      "default": null,
      "description": "Absolute floor on `area_m2` (square metres). Distinct from the target-relative `area_band_pct` used by the analytical surfaces; this is for Browse / Watchdog where there is no target to band around.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 300,
        "step": 5
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": [
        "area_min",
        "areaMin"
      ]
    },
    {
      "id": "max_area_m2",
      "type": "float",
      "pg_column": "area_m2",
      "default": null,
      "description": "Absolute ceiling on `area_m2` (square metres). See `min_area_m2`.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 300,
        "step": 5
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": [
        "area_max",
        "areaMax"
      ]
    },
    {
      "id": "min_estate_area",
      "type": "float",
      "pg_column": "estate_area",
      "default": null,
      "description": "Lower bound on plot area in m². Mostly relevant for `category_main='dum'` (houses) and `pozemek` (land) — apartments usually have null estate_area.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 5000,
        "step": 50
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": [
        "estate_min"
      ]
    },
    {
      "id": "max_estate_area",
      "type": "float",
      "pg_column": "estate_area",
      "default": null,
      "description": "Upper bound on plot area in m². See `min_estate_area`.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 5000,
        "step": 50
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": [
        "estate_max"
      ]
    },
    {
      "id": "min_usable_area",
      "type": "float",
      "pg_column": "usable_area",
      "default": null,
      "description": "Lower bound on usable_area in m². Distinct from `area_m2` (the headline) — usable area excludes balconies, cellars, parking. Often smaller than `area_m2` for the same listing.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 500,
        "step": 5
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": [
        "usable_min"
      ]
    },
    {
      "id": "max_usable_area",
      "type": "float",
      "pg_column": "usable_area",
      "default": null,
      "description": "Upper bound on usable_area in m². See `min_usable_area`.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 500,
        "step": 5
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": [
        "usable_max"
      ]
    },
    {
      "id": "min_garden_area",
      "type": "float",
      "pg_column": "garden_area",
      "default": null,
      "description": "Lower bound on garden_area in m². Populated by the scraper for listings with a dedicated garden plot — usually houses and ground-floor apartments.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 5000,
        "step": 50
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "max_garden_area",
      "type": "float",
      "pg_column": "garden_area",
      "default": null,
      "description": "Upper bound on garden_area in m². See `min_garden_area`.",
      "category": "Property",
      "ui_control": "range_slider",
      "agendas": [
        "browse",
        "comparables",
        "defaults",
        "estimation",
        "neighborhood",
        "velocity",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 5000,
        "step": 50
      },
      "unit": "m²",
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "locality_district_id",
      "type": "int",
      "pg_column": "locality_district_id",
      "default": null,
      "description": "Sreality district id. Stable across district renames (unlike the human-readable `district` text). Useful for constraining a cohort to one municipality without geocoding.",
      "category": "Spatial",
      "ui_control": "number_input",
      "agendas": [
        "comparables",
        "estimation",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "locality_region_id",
      "type": "int",
      "pg_column": "locality_region_id",
      "default": null,
      "description": "Sreality region id. Broader than district.",
      "category": "Spatial",
      "ui_control": "number_input",
      "agendas": [
        "comparables",
        "estimation",
        "velocity",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "tags",
      "type": "int_list",
      "pg_column": null,
      "default": null,
      "description": "Operator-curated tag ids. AND-semantics — a listing matches only if it carries every tag in the list. Tag ids are stable across renames.",
      "category": "Curation",
      "ui_control": "multiselect",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "city_index_rules",
      "type": "city_index_rule_list",
      "pg_column": null,
      "default": null,
      "description": "Filter listings to those located in a curated city whose qualitative indexes meet every rule in the list. Each rule is `{index_name: str, op: '>='|'<=', value: float}`. Rules are AND'd. `index_name` is a slug from `city_index_definitions_public` (e.g. `bezpecnost`, `prakticti_lekari`). Listings outside the curated city set (matched via ST_DWithin to the nearest curated city's centroid using its `default_radius_m`) are excluded when this filter is active.",
      "category": "City quality",
      "ui_control": "city_index_rules",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "min_city_population",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "Lower bound on the listing's curated-city population (latest `city_population` row). Applies only to listings inside the curated-city footprint; others fall through to the city-quality activation check.",
      "category": "City quality",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 1500000,
        "step": 1000
      },
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "max_city_population",
      "type": "int",
      "pg_column": null,
      "default": null,
      "description": "Upper bound on curated-city population. See `min_city_population`.",
      "category": "City quality",
      "ui_control": "number_input",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": {
        "min": 0,
        "max": 1500000,
        "step": 1000
      },
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "near_city_proximity",
      "type": "near_city_proximity",
      "pg_column": null,
      "default": null,
      "description": "Restrict listings to those within `radius_km` km of any curated city matching the inner index rules and the optional population minimum. Composite shape: `{index_rules: [{index_name, op, value}, ...], population_min: int|null, radius_km: int}`. Index rules are AND'd. Implementation uses `ST_DWithin(listing.geom, ST_Union(matching_cities.centroid), radius_km*1000)`.",
      "category": "City quality",
      "ui_control": "near_city_rule",
      "agendas": [
        "browse",
        "watchdog"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    },
    {
      "id": "include_unreliable",
      "type": "bool",
      "pg_column": null,
      "default": false,
      "description": "When false (default), excludes listings whose detail fetches have been given up (`listing_fetch_failures.given_up = true`). Set true only for forensic queries where you want every row regardless of fetch state.",
      "category": "Status",
      "ui_control": "boolean",
      "agendas": [
        "comparables",
        "estimation",
        "velocity"
      ],
      "constraints": null,
      "unit": null,
      "enum_values": null,
      "aliases": []
    }
  ]
};

export function filterById(id: string): FilterDef | undefined {
  return FILTER_REGISTRY.filters.find((f) => f.id === id);
}

export function filtersForAgenda(agenda: Agenda): FilterDef[] {
  return FILTER_REGISTRY.filters.filter((f) => f.agendas.includes(agenda));
}

export const AGENDAS = FILTER_REGISTRY.agendas;
export const CATEGORIES = FILTER_REGISTRY.categories;
export const UI_CONTROLS = FILTER_REGISTRY.ui_controls;
