// AUTOGENERATED — DO NOT EDIT.
// Source of truth: the .github/workflows/*.yml files.
// Regenerate with: python scripts/generate_workflow_docs.py
//
// CI runs `--check` and fails on drift, so adding, removing, or editing
// a workflow must be paired with a fresh regen in the same commit. The
// per-workflow `description` is the first paragraph of the leading
// comment block at the top of each YAML file.

export interface WorkflowInput {
  name: string;
  description: string;
  required: boolean;
  type: string;
  default: string | null;
  options: string[] | null;
}

export interface WorkflowSchedule {
  cron: string;
  human: string;
}

export interface WorkflowDoc {
  filename: string;
  name: string;
  description: string;
  manual: boolean;
  schedules: WorkflowSchedule[];
  onPush: boolean;
  onPullRequest: boolean;
  paths: string[] | null;
  inputs: WorkflowInput[];
  secrets: string[];
  concurrencyGroup: string | null;
  cancelInProgress: boolean | null;
  timeoutMinutes: number | null;
  permissions: string | null;
  runsUrl: string;
  sourceUrl: string;
}

export const WORKFLOW_DOCS: WorkflowDoc[] = [
  {
    "filename": "aggregate_condition_markers.yml",
    "name": "Dev: aggregate condition markers (one-off Phase A bootstrap)",
    "description": "Runs scripts/aggregate_condition_markers.py against the live `listing_marker_extractions` rows to produce data/condition_markers_v1.json, then commits the JSON back to the running branch so the operator can review it in the PR diff.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "output_path",
        "description": "Output JSON path inside the repo",
        "required": true,
        "type": "string",
        "default": "data/condition_markers_v1.json",
        "options": null
      },
      {
        "name": "min_cluster_count",
        "description": "Drop clusters whose total count is below this",
        "required": true,
        "type": "string",
        "default": "3",
        "options": null
      },
      {
        "name": "similarity_threshold",
        "description": "difflib ratio merge threshold (0.0-1.0)",
        "required": true,
        "type": "string",
        "default": "0.85",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 15,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/aggregate_condition_markers.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/aggregate_condition_markers.yml"
  },
  {
    "filename": "build-extension.yml",
    "name": "CI: build Chrome extension",
    "description": "Builds the chrome-extension/ bundle and uploads dist/ as a workflow artifact you can download from the Actions tab. Keeps the build off the operator's laptop (no local Node install needed).",
    "manual": true,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/build-extension.yml",
      "chrome-extension/**"
    ],
    "inputs": [],
    "secrets": [
      "EXT_API_BASE_URL",
      "EXT_API_TOKEN"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": null,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/build-extension.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/build-extension.yml"
  },
  {
    "filename": "compute_image_phash.yml",
    "name": "Compute image pHash (multi-portal dedup)",
    "description": "Backfills images.phash (a 64-bit perceptual dHash per stored image) for the Tier-2 dedup sweep's cheap image corroborator. Downloads stored bytes from R2, hashes them, writes images.phash. Idempotent + resumable; a no-op if R2 env vars are missing.",
    "manual": true,
    "schedules": [
      {
        "cron": "20 */6 * * *",
        "human": "Every 6 hours at :20"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Max images hashed per run",
        "required": false,
        "type": "string",
        "default": "5000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report the pending count and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "compute-image-phash",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/compute_image_phash.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/compute_image_phash.yml"
  },
  {
    "filename": "condition_score_batches.yml",
    "name": "Scraping: Sreality condition scoring (batch API)",
    "description": "Phase 1.8b — async condition scoring via the Anthropic Message Batches API (50% cheaper than the synchronous condition_scores.yml job). Two modes, selected by the `mode` input:",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "mode",
        "description": "submit a new batch, or ingest completed ones",
        "required": true,
        "type": "choice",
        "default": "ingest",
        "options": [
          "ingest",
          "submit"
        ]
      },
      {
        "name": "region_ids",
        "description": "[submit] Comma-separated locality_region_id list (empty = no filter)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "limit",
        "description": "[submit] Max listings to put in the batch",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "n_images",
        "description": "[submit] Images per listing (0 = text-only, matches production)",
        "required": false,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "max_age_days",
        "description": "[submit] Only listings seen within this many days (0 = no filter)",
        "required": false,
        "type": "string",
        "default": "30",
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "condition-score-batches",
    "cancelInProgress": false,
    "timeoutMinutes": 60,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/condition_score_batches.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/condition_score_batches.yml"
  },
  {
    "filename": "condition_scores.yml",
    "name": "Scraping: Sreality condition scoring (hourly + manual backfill)",
    "description": "Decoupled condition-scoring job. Scores building/apartment condition (1..5) for active listings whose latest snapshot doesn't yet have a row in `listing_condition_scores`, writing both the cache row AND the two listings.*_condition_level columns in one transaction per listing (autocommit — every successful score commits independently, so a timeout or cancel preserves the rows already done). Resumable: scored listings drop out of the next selection.",
    "manual": true,
    "schedules": [
      {
        "cron": "30 * * * *",
        "human": "Every hour at :30"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "region_ids",
        "description": "Comma-separated locality_region_id list (empty = no region filter)",
        "required": false,
        "type": "string",
        "default": "10,11,2,13",
        "options": null
      },
      {
        "name": "limit",
        "description": "Maximum number of listings to score in this run",
        "required": true,
        "type": "string",
        "default": "500",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 disables vision; default 0 matches discovery)",
        "required": true,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "10",
        "options": null
      },
      {
        "name": "max_age_days",
        "description": "Only score listings whose last_seen_at is within this many days (0 = no freshness filter)",
        "required": true,
        "type": "string",
        "default": "30",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Print first 20 pending IDs and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "condition-scoring",
    "cancelInProgress": false,
    "timeoutMinutes": 55,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/condition_scores.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/condition_scores.yml"
  },
  {
    "filename": "dedup_sweep.yml",
    "name": "Tier-2 dedup sweep (multi-portal)",
    "description": "Cross-source dedup sweep (multi-portal dedup PR3). Finds property pairs the cheap insert-time Tier-1 matcher missed -- the same real-world property listed on two portals whose coords/area/price differ enough to slip Tier-1's tight gate -- scores each through a confidence ladder (disposition equivalence -> address similarity -> pHash [PR5] -> vision), then auto-merges the high-confidence few (reversible + audited) and queues the rest for the /dedup review UI. CROSS-SOURCE ONLY: same-portal pairs are legitimately distinct units and never touched.",
    "manual": true,
    "schedules": [
      {
        "cron": "45 3 * * *",
        "human": "Daily at 03:45 UTC"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Max candidate pairs generated per run",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "max_auto_merges",
        "description": "Cap auto-merges per run (overflow is queued)",
        "required": false,
        "type": "string",
        "default": "200",
        "options": null
      },
      {
        "name": "max_vision_calls",
        "description": "Cap vision corroborations per run (0 = vision off)",
        "required": false,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report candidate-pair count and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "dedup-sweep",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/dedup_sweep.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/dedup_sweep.yml"
  },
  {
    "filename": "detail_drain.yml",
    "name": "Scraping: Sreality detail drain (Phase 2)",
    "description": "The slow half of the Phase-2 cadence split. Claims a bounded slice of listing_detail_queue (enqueued by index_walk.yml), fetches each listing's detail on a rate-limited worker pool, and writes them in batches via the set-based write_detail_batch (one transaction per ~100 listings) — targeting ~0.1-0.2 s/listing versus the ~1.5 s of the legacy per-listing write. New listings land with property_id NULL; the Tier-1 matcher is deferred to the recompute_property_stats straggler-attach phase.",
    "manual": true,
    "schedules": [
      {
        "cron": "*/15 * * * *",
        "human": "Every 15 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_detail_refetches",
        "description": "Cap listings claimed + fetched this run (blank = 12000)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_workers",
        "description": "Concurrent detail-fetch workers (blank = 8)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_rate",
        "description": "Global detail-fetch rate cap, req/s (blank = 6.0)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report the claimable queue depth and exit without claiming",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_SESSION_URL",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-detail-drain",
    "cancelInProgress": false,
    "timeoutMinutes": 50,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/detail_drain.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/detail_drain.yml"
  },
  {
    "filename": "discover_condition_markers.yml",
    "name": "Dev: discover condition markers (one-off Phase A bootstrap)",
    "description": "One-off Phase A driver for the building/apartment condition-scoring feature. Runs scripts/discover_condition_markers.py against the real Supabase DB and the Anthropic API to mine Czech condition markers from a stratified sample of listings.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Maximum number of listings to extract markers for",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 disables vision; default 5)",
        "required": true,
        "type": "string",
        "default": "5",
        "options": null
      },
      {
        "name": "per_cell_cap",
        "description": "Max picks per stratification cell",
        "required": true,
        "type": "string",
        "default": "6",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "80",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Print sample and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 180,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/discover_condition_markers.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/discover_condition_markers.yml"
  },
  {
    "filename": "fetch-fixtures.yml",
    "name": "Fixtures: source HTML (anonymized)",
    "description": "Manual trigger only. Fetches each listing URL, runs the anonymization in scripts/fetch_and_anonymize_fixtures.py, and commits the resulting fixtures to the current branch. Operator runs this once per source refresh; tests then read the saved files instead of hitting the internet.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "bezrealitky_url",
        "description": "bezrealitky.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://www.bezrealitky.cz/nemovitosti-byty-domy/547214-nabidka-pronajem-bytu-pod-harfou-hlavni-mesto-praha",
        "options": null
      },
      {
        "name": "idnes_url",
        "description": "reality.idnes.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://reality.idnes.cz/detail/pronajem/byt/brno-veveri/69f8c898e58c5ab7d70f3505/",
        "options": null
      },
      {
        "name": "remax_url",
        "description": "remax-czech.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://www.remax-czech.cz/reality/detail/438735/pronajem-bytu-1-kk-v-osobnim-vlastnictvi-31-m2-praha-8-liben",
        "options": null
      },
      {
        "name": "bazos_index_url",
        "description": "reality.bazos.cz search/index URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://reality.bazos.cz/prodam/byt/",
        "options": null
      },
      {
        "name": "bazos_detail_url",
        "description": "reality.bazos.cz single-listing detail URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch-fixtures.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch-fixtures.yml"
  },
  {
    "filename": "fetch_sreality_fixtures.yml",
    "name": "Fixtures: sreality v1 JSON",
    "description": "Manual trigger only. Fetches a real search response + one real detail response from a GitHub runner IP (this repo's dev sandbox is 403'd by sreality), scrubs emails/phone numbers, and commits the result as tests/fixtures/sample_search.json + sample_listing.json on the current branch. The live /api/v1/estates API is snake_case (id key `hash_id`, detail wrapped under `result`); these fixtures pin the true shape so the parser tests guard reality instead of the HAR-derived camelCase guess.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "category_main",
        "description": "category_main_cb (1=byt, 2=dum, 4=komercni)",
        "required": false,
        "type": "string",
        "default": "1",
        "options": null
      },
      {
        "name": "category_type",
        "description": "category_type_cb (1=prodej, 2=pronajem)",
        "required": false,
        "type": "string",
        "default": "1",
        "options": null
      },
      {
        "name": "detail_id",
        "description": "Override detail hash_id (blank = first search result)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch_sreality_fixtures.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch_sreality_fixtures.yml"
  },
  {
    "filename": "frontend-build.yml",
    "name": "CI: frontend build",
    "description": "Builds the frontend/ Vite SPA on every push or pull request that touches frontend code, to catch build/type errors before deploy. Type-checks, builds the production bundle, and reports gzipped chunk sizes (warning if the initial JS chunk exceeds the 500 kB budget). Does not deploy.",
    "manual": false,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/frontend-build.yml",
      "frontend/**"
    ],
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": null,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/frontend-build.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/frontend-build.yml"
  },
  {
    "filename": "images.yml",
    "name": "Scraping: Sreality image backlog drain",
    "description": "THE image-download workflow. Images are fully decoupled from the scrape (scrape.yml is index + detail only), so this is the single owner of all image downloading — both newest active listings and the deep INACTIVE/ historical backlog. Runs the image-download phase only, every 2 hours.",
    "manual": true,
    "schedules": [
      {
        "cron": "0 */2 * * *",
        "human": "Every 2 hours"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_image_downloads",
        "description": "Override images-per-run cap (blank = 0 = drain to empty / suspicious-stop)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent workers (blank = 32)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "images_active_only",
        "description": "Restrict to active listings only. Default false: drain the full backlog incl. inactive (the hourly scrape already covers active).",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "images-backfill",
    "cancelInProgress": false,
    "timeoutMinutes": 110,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/images.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/images.yml"
  },
  {
    "filename": "index_walk.yml",
    "name": "Scraping: Sreality index walk (Phase 2)",
    "description": "The fast half of the Phase-2 cadence split. Walks the COMPLETE index of all six category pairs, bumps last_seen on still-listed ids (touch), flips delisted ones to is_active=false (mark_inactive, under the completeness guard), and enqueues new + price-changed ids into listing_detail_queue for the asynchronous detail-drain. It does NO detail fetching, so it finishes in minutes and delistings surface fast — decoupled from the slow per-listing write that used to drag it.",
    "manual": true,
    "schedules": [
      {
        "cron": "*/15 * * * *",
        "human": "Every 15 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Walk the index and log enqueue intent, but write nothing",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-index-walk",
    "cancelInProgress": false,
    "timeoutMinutes": 25,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/index_walk.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/index_walk.yml"
  },
  {
    "filename": "ingest_boundaries.yml",
    "name": "Data: ingest admin boundaries",
    "description": "Loads ČÚZK RÚIAN administrative-unit polygons (kraj / okres / obec / KÚ) into the admin_boundaries table. Manual-only; boundaries change rarely (a few municipal mergers / cadastral re-alignments per year), so there is no cron. Re-run when ČÚZK publishes a notable update or when the operator wants to bring in newly-created units.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "source_url",
        "description": "RÚIAN SHP zip URL (from ČÚZK ATOM feed)",
        "required": true,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "levels",
        "description": "Levels to load (comma-separated). Default: all four.",
        "required": false,
        "type": "string",
        "default": "kraj,okres,obec,ku",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Parse and validate only; do not write to DB.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "skip_spatial_join",
        "description": "Skip the listings -> sreality_id population step.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "no_truncate",
        "description": "Skip TRUNCATE; upsert into existing rows instead.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/ingest_boundaries.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/ingest_boundaries.yml"
  },
  {
    "filename": "migrations.yml",
    "name": "CI: migration smoke-test",
    "description": "Applies the full migrations/ chain (001 -> latest) to a throwaway Postgres + PostGIS container whenever anything under migrations/ changes, catching a migration that does not apply cleanly before it reaches the production Supabase database (there is no staging DB). It pre-creates the Supabase roles the migrations GRANT to (anon / authenticated / service_role) and the pg_trgm extension migrations 067 / 074 rely on, applies every *.sql in numeric order, then runs a small sanity query. Hermetic: no secrets, never touches production.",
    "manual": true,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/migrations.yml",
      "migrations/**",
      "scripts/ci_db_bootstrap.sql"
    ],
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 10,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/migrations.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/migrations.yml"
  },
  {
    "filename": "property_maintenance.yml",
    "name": "Jobs: property maintenance (incremental)",
    "description": "Phase 3 of the scaling roadmap: real-time properties. This is the FAST, FREQUENT half of property maintenance — the dirty-set incremental pass. It runs scripts/recompute_property_stats --incremental, which:",
    "manual": true,
    "schedules": [
      {
        "cron": "*/5 * * * *",
        "human": "Every 5 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "batch_size",
        "description": "Properties recomputed per statement",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report straggler + dirty + property counts and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-property-maintenance",
    "cancelInProgress": false,
    "timeoutMinutes": 10,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/property_maintenance.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/property_maintenance.yml"
  },
  {
    "filename": "recompute_property_stats.yml",
    "name": "Jobs: recompute property stats (daily full reconcile)",
    "description": "DAILY FULL SWEEP for the canonical `properties` parent. Attaches any straggler unlinked listings (incl. the one-time native-id backfill), then recomputes EVERY property's is_active rollup, source / site counts, first/last-seen span, representative child, current price, and the price-history aggregates (drop / rise counts, max drop %) from the union of its children's snapshots. Finally it clears the dirty_properties queue (everything was just recomputed).",
    "manual": true,
    "schedules": [
      {
        "cron": "15 4 * * *",
        "human": "Daily at 04:15 UTC"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "batch_size",
        "description": "Properties recomputed per statement",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report straggler + dirty + property counts and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-property-maintenance",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/recompute_property_stats.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/recompute_property_stats.yml"
  },
  {
    "filename": "refresh_population.yml",
    "name": "Data: refresh city populations (Wikidata)",
    "description": "Pulls the latest population reading for every curated city from Wikidata's public SPARQL endpoint, writes data/csu_population_<year>.csv, and commits it back to the branch. The next run of `Seed curated cities` will pick the CSV up and upsert into `city_population`.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "year",
        "description": "Latest year to accept (e.g. 2024, 2025)",
        "required": false,
        "type": "string",
        "default": "2024",
        "options": null
      },
      {
        "name": "commit",
        "description": "Commit the regenerated CSV back to the branch",
        "required": false,
        "type": "choice",
        "default": "true",
        "options": [
          "true",
          "false"
        ]
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 10,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/refresh_population.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/refresh_population.yml"
  },
  {
    "filename": "scrape.yml",
    "name": "Scraping: Sreality combined walk (Phase-2 fallback, dispatch-only)",
    "description": "DISPATCH-ONLY FALLBACK as of Phase 2. The hourly cron was removed: the live pipeline is now the cadence split — index_walk.yml (fast, frequent, marks delistings + enqueues) feeds detail_drain.yml (async, batched writes). This combined index+detail walk (_run_full) is kept intact as the instant revert: if the split misbehaves, re-add `schedule: - cron: \"0 * * * *\"` here and disable the two new crons — no code change, the proven pipeline is back. It also remains the way to run an ad-hoc full walk by hand.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Cap number of listings scraped (blank = all). Applies across the whole run, not per category. A capped run records run_type='delta' and skips mark_inactive.",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Don't write to the database",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "detail_only",
        "description": "Refetch a single listing by id (skips index)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "no_image_downloads",
        "description": "Skip image download phase",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "max_detail_refetches",
        "description": "Override global detail-refetches-per-run cap (blank = 4000)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "max_detail_refetches_per_category",
        "description": "Override per-category detail-refetches cap (blank = 1200)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "max_image_downloads",
        "description": "Override images-per-run cap (blank = 0 = drain active to empty / suspicious-stop)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent image workers (blank = 16)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_workers",
        "description": "Override concurrent detail-fetch workers (blank = 8)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_rate",
        "description": "Override global detail-fetch rate cap, req/s (blank = 6.0)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SCRAPE_CHAIN_TOKEN",
      "SUPABASE_DB_SESSION_URL",
      "SUPABASE_DB_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "concurrencyGroup": "sreality-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 90,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape.yml"
  },
  {
    "filename": "scrape_bazos.yml",
    "name": "Scraping: Bazos crawler (pilot)",
    "description": "Scheduled (every 6h) + manual crawler for reality.bazos.cz (multi-portal slice 3b). Walks one bazos category's index, fetches each listing detail, stages the raw HTML in portal_raw_pages, parses it, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching).",
    "manual": true,
    "schedules": [
      {
        "cron": "30 */6 * * *",
        "human": "Every 6 hours at :30"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "sale_type",
        "description": "prodam (sale) or pronajmu (rent)",
        "required": false,
        "type": "choice",
        "default": "prodam",
        "options": [
          "prodam",
          "pronajmu"
        ]
      },
      {
        "name": "category",
        "description": "bazos category segment",
        "required": false,
        "type": "choice",
        "default": "byt",
        "options": [
          "byt",
          "dum",
          "pozemky",
          "nebytove",
          "ostatni"
        ]
      },
      {
        "name": "locality",
        "description": "locality filter (e.g. Praha); blank = nationwide",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "radius_km",
        "description": "radius around locality in km (blank = none)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_pages",
        "description": "cap index pages walked (pilot safety)",
        "required": false,
        "type": "string",
        "default": "2",
        "options": null
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bazos-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 20,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_bazos.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_bazos.yml"
  },
  {
    "filename": "scrape_bezrealitky.yml",
    "name": "Scraping: Bezrealitky scraper (pilot)",
    "description": "Scheduled (every 6h) + manual scraper for bezrealitky.cz on the shared portal framework. Bezrealitky is a JSON-API portal (public GraphQL at api.bezrealitky.cz) like sreality: the index walk pages listAdverts and enqueues new/price-changed ids into listing_detail_queue, then the detail drain fetches advert(id), parses to a ScrapedListing, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching).",
    "manual": true,
    "schedules": [
      {
        "cron": "45 */6 * * *",
        "human": "Every 6 hours at :45"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap index pages per category (ad-hoc partial; suppresses mark_inactive). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "2.0",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bezrealitky-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_bezrealitky.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_bezrealitky.yml"
  },
  {
    "filename": "scrape_idnes.yml",
    "name": "Scraping: iDNES Reality scraper (pilot)",
    "description": "Scheduled (every 6h) + manual scraper for reality.idnes.cz on the shared portal framework. One job runs both phases: an index walk pages the HTML search results and enqueues new/price-changed ids into listing_detail_queue, then a detail drain fetches each listing page, parses to a ScrapedListing, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching).",
    "manual": true,
    "schedules": [
      {
        "cron": "15 */6 * * *",
        "human": "Every 6 hours at :15"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap index pages per category (ad-hoc partial; suppresses mark_inactive). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run",
        "required": false,
        "type": "string",
        "default": "6000",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "3.0",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "idnes-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 55,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_idnes.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_idnes.yml"
  },
  {
    "filename": "seed_condition_settings.yml",
    "name": "Data: seed condition settings (rubric + markers)",
    "description": "One-shot workflow that populates the two large app_settings rows created by migration 072 — `llm_condition_rubric` and `llm_condition_marker_dictionary` — from the committed JSON files (data/condition_rubric_v1.json + data/condition_markers_curated.json).",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Print sizes and exit without UPDATEing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/seed_condition_settings.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/seed_condition_settings.yml"
  },
  {
    "filename": "seed_curated_cities.yml",
    "name": "Data: seed curated cities",
    "description": "One-shot workflow that geocodes the 206 cities in data/obce_v_datech_2025.csv via Mapy.cz, then writes them into curated_cities + city_index_definitions + city_index_revisions + city_index_values (+ city_population if the CSV is present).",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Plan only — geocode, but skip DB writes",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      },
      {
        "name": "commit_geocodes",
        "description": "Commit data/curated_cities_geocoded.json back to the branch",
        "required": false,
        "type": "choice",
        "default": "true",
        "options": [
          "true",
          "false"
        ]
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 15,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/seed_curated_cities.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/seed_curated_cities.yml"
  },
  {
    "filename": "smoke_agent.yml",
    "name": "Dev: agent smoke test",
    "description": "Manual invocation only. Runs scripts/smoke_agent.py against the real Supabase DB and a real LLM provider. Picks a recent Prague 2+kk rental by default; --sreality-id overrides. Real LLM credits are spent — typically under $0.10 per run.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "provider",
        "description": "LLM provider (anthropic or gemini)",
        "required": true,
        "type": "choice",
        "default": "anthropic",
        "options": [
          "anthropic",
          "gemini"
        ]
      },
      {
        "name": "sreality_id",
        "description": "Specific listing id to estimate (leave blank to pick a recent Prague 2+kk)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "skill",
        "description": "Skill row name",
        "required": false,
        "type": "string",
        "default": "rental_estimator_v1",
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "GEMINI_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/smoke_agent.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/smoke_agent.yml"
  },
  {
    "filename": "test.yml",
    "name": "CI: tests",
    "description": "CI test suite, runs on every push and pull request. Two parallel jobs: a Python job (verifies the filter-registry and workflow-docs codegen are fresh, then runs pytest) and a frontend job (TypeScript type-check + vitest pure-function tests). This is the build gate for every branch.",
    "manual": false,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": null,
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/test.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/test.yml"
  }
];
