// AUTOGENERATED — DO NOT EDIT.
// Source of truth: the .github/workflows/*.yml files.
// Regenerate with: python scripts/generate_workflow_docs.py
//
// CI runs `--check` and fails on drift, so adding, removing, or editing
// a workflow must be paired with a fresh regen in the same commit. The
// per-workflow `description` is the first paragraph of the leading
// comment block at the top of each YAML file.

export interface WorkflowInput {
  name: string;
  description: string;
  required: boolean;
  type: string;
  default: string | null;
  options: string[] | null;
}

export interface WorkflowSchedule {
  cron: string;
  human: string;
}

export interface WorkflowDoc {
  filename: string;
  name: string;
  description: string;
  manual: boolean;
  schedules: WorkflowSchedule[];
  onPush: boolean;
  onPullRequest: boolean;
  paths: string[] | null;
  inputs: WorkflowInput[];
  secrets: string[];
  concurrencyGroup: string | null;
  cancelInProgress: boolean | null;
  timeoutMinutes: number | null;
  permissions: string | null;
  runsUrl: string;
  sourceUrl: string;
}

export const WORKFLOW_DOCS: WorkflowDoc[] = [
  {
    "filename": "aggregate_condition_markers.yml",
    "name": "Aggregate condition markers (Phase A review prep)",
    "description": "Runs scripts/aggregate_condition_markers.py against the live `listing_marker_extractions` rows to produce data/condition_markers_v1.json, then commits the JSON back to the running branch so the operator can review it in the PR diff.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "output_path",
        "description": "Output JSON path inside the repo",
        "required": true,
        "type": "string",
        "default": "data/condition_markers_v1.json",
        "options": null
      },
      {
        "name": "min_cluster_count",
        "description": "Drop clusters whose total count is below this",
        "required": true,
        "type": "string",
        "default": "3",
        "options": null
      },
      {
        "name": "similarity_threshold",
        "description": "difflib ratio merge threshold (0.0-1.0)",
        "required": true,
        "type": "string",
        "default": "0.85",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 15,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/aggregate_condition_markers.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/aggregate_condition_markers.yml"
  },
  {
    "filename": "backfill_condition_scores.yml",
    "name": "Backfill condition scores (Phase B2)",
    "description": "Manual workflow that backfills building/apartment condition scores for active listings. Resumable — each invocation processes only listings whose latest snapshot doesn't yet have a row in `listing_condition_scores`. The script writes to both the cache table AND the two listings.*_condition_level columns in one transaction per listing (autocommit=True on the connection means every successful score commits independently — a workflow timeout or cancel preserves the rows already done).",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "region_ids",
        "description": "Comma-separated locality_region_id list (empty = no region filter)",
        "required": false,
        "type": "string",
        "default": "10,11,2,13",
        "options": null
      },
      {
        "name": "limit",
        "description": "Maximum number of listings to score in this run",
        "required": true,
        "type": "string",
        "default": "500",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 disables vision; default 0 matches discovery)",
        "required": true,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "10",
        "options": null
      },
      {
        "name": "max_age_days",
        "description": "Only score listings whose last_seen_at is within this many days (0 = no freshness filter)",
        "required": true,
        "type": "string",
        "default": "30",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Print first 20 pending IDs and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 350,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/backfill_condition_scores.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/backfill_condition_scores.yml"
  },
  {
    "filename": "build-extension.yml",
    "name": "Build Chrome extension",
    "description": "Builds the chrome-extension/ bundle and uploads dist/ as a workflow artifact you can download from the Actions tab. Keeps the build off the operator's laptop (no local Node install needed).",
    "manual": true,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/build-extension.yml",
      "chrome-extension/**"
    ],
    "inputs": [],
    "secrets": [
      "EXT_API_BASE_URL",
      "EXT_API_TOKEN"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": null,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/build-extension.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/build-extension.yml"
  },
  {
    "filename": "diagnose_block.yml",
    "name": "Scraping: recon sreality new API (probe)",
    "description": "Free, zero-secret reconnaissance for the scraper rewrite. We already proved the old /api/cs/v2/estates API is gone (404) and the new Next.js site is reachable from GitHub IPs. This run pins down the two open questions for the new client, from a real GitHub runner IP (this sandbox's own IP is 403'd by sreality):",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "samples",
        "description": "Number of parallel IP samples (1-10)",
        "required": false,
        "type": "string",
        "default": "3",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 6,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/diagnose_block.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/diagnose_block.yml"
  },
  {
    "filename": "discover_condition_markers.yml",
    "name": "Discover condition markers (Phase A)",
    "description": "One-off Phase A driver for the building/apartment condition-scoring feature. Runs scripts/discover_condition_markers.py against the real Supabase DB and the Anthropic API to mine Czech condition markers from a stratified sample of listings.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Maximum number of listings to extract markers for",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 disables vision; default 5)",
        "required": true,
        "type": "string",
        "default": "5",
        "options": null
      },
      {
        "name": "per_cell_cap",
        "description": "Max picks per stratification cell",
        "required": true,
        "type": "string",
        "default": "6",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "80",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Print sample and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 180,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/discover_condition_markers.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/discover_condition_markers.yml"
  },
  {
    "filename": "fetch-fixtures.yml",
    "name": "Fetch + anonymize source HTML fixtures",
    "description": "Manual trigger only. Fetches each listing URL, runs the anonymization in scripts/fetch_and_anonymize_fixtures.py, and commits the resulting fixtures to the current branch. Operator runs this once per source refresh; tests then read the saved files instead of hitting the internet.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "bezrealitky_url",
        "description": "bezrealitky.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://www.bezrealitky.cz/nemovitosti-byty-domy/547214-nabidka-pronajem-bytu-pod-harfou-hlavni-mesto-praha",
        "options": null
      },
      {
        "name": "idnes_url",
        "description": "reality.idnes.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://reality.idnes.cz/detail/pronajem/byt/brno-veveri/69f8c898e58c5ab7d70f3505/",
        "options": null
      },
      {
        "name": "remax_url",
        "description": "remax-czech.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://www.remax-czech.cz/reality/detail/438735/pronajem-bytu-1-kk-v-osobnim-vlastnictvi-31-m2-praha-8-liben",
        "options": null
      },
      {
        "name": "bazos_index_url",
        "description": "reality.bazos.cz search/index URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://reality.bazos.cz/prodam/byt/",
        "options": null
      },
      {
        "name": "bazos_detail_url",
        "description": "reality.bazos.cz single-listing detail URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch-fixtures.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch-fixtures.yml"
  },
  {
    "filename": "fetch_sreality_fixtures.yml",
    "name": "Scraping: fetch sreality v1 JSON fixtures",
    "description": "Manual trigger only. Fetches a real search response + one real detail response from a GitHub runner IP (this repo's dev sandbox is 403'd by sreality), scrubs emails/phone numbers, and commits the result as tests/fixtures/sample_search.json + sample_listing.json on the current branch. The live /api/v1/estates API is snake_case (id key `hash_id`, detail wrapped under `result`); these fixtures pin the true shape so the parser tests guard reality instead of the HAR-derived camelCase guess.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "category_main",
        "description": "category_main_cb (1=byt, 2=dum, 4=komercni)",
        "required": false,
        "type": "string",
        "default": "1",
        "options": null
      },
      {
        "name": "category_type",
        "description": "category_type_cb (1=prodej, 2=pronajem)",
        "required": false,
        "type": "string",
        "default": "1",
        "options": null
      },
      {
        "name": "detail_id",
        "description": "Override detail hash_id (blank = first search result)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch_sreality_fixtures.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch_sreality_fixtures.yml"
  },
  {
    "filename": "frontend-build.yml",
    "name": "Frontend build",
    "description": "Builds the frontend/ Vite SPA on every push or pull request that touches frontend code, to catch build/type errors before deploy. Type-checks, builds the production bundle, and reports gzipped chunk sizes (warning if the initial JS chunk exceeds the 500 kB budget). Does not deploy.",
    "manual": false,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/frontend-build.yml",
      "frontend/**"
    ],
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": null,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/frontend-build.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/frontend-build.yml"
  },
  {
    "filename": "images.yml",
    "name": "Scraping: Sreality image backlog drain",
    "description": "Backfill workflow that runs only the image-download phase every 2 hours. Pairs with scrape.yml (which now also drains to empty after the nightly index walk) to keep \"missed images\" close to zero.",
    "manual": true,
    "schedules": [
      {
        "cron": "0 */2 * * *",
        "human": "Every 2 hours"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_image_downloads",
        "description": "Override images-per-run cap (blank = 0 = drain to empty / suspicious-stop)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent workers (blank = 32)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "images_active_only",
        "description": "Restrict to active listings (default true). Untick to drain inactive backlog too.",
        "required": false,
        "type": "boolean",
        "default": "true",
        "options": null
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "images-backfill",
    "cancelInProgress": false,
    "timeoutMinutes": 110,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/images.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/images.yml"
  },
  {
    "filename": "ingest_boundaries.yml",
    "name": "Ingest admin boundaries",
    "description": "Loads ČÚZK RÚIAN administrative-unit polygons (kraj / okres / obec / KÚ) into the admin_boundaries table. Manual-only; boundaries change rarely (a few municipal mergers / cadastral re-alignments per year), so there is no cron. Re-run when ČÚZK publishes a notable update or when the operator wants to bring in newly-created units.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "source_url",
        "description": "RÚIAN SHP zip URL (from ČÚZK ATOM feed)",
        "required": true,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "levels",
        "description": "Levels to load (comma-separated). Default: all four.",
        "required": false,
        "type": "string",
        "default": "kraj,okres,obec,ku",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Parse and validate only; do not write to DB.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "skip_spatial_join",
        "description": "Skip the listings -> sreality_id population step.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "no_truncate",
        "description": "Skip TRUNCATE; upsert into existing rows instead.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/ingest_boundaries.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/ingest_boundaries.yml"
  },
  {
    "filename": "recompute_property_stats.yml",
    "name": "Recompute property stats (Slice 1)",
    "description": "Async recompute job for the canonical `properties` parent (multi-portal dedup track, Slice 1). Attaches any straggler unlinked listings, then recomputes every property's is_active rollup, source / site counts, first/last-seen span, representative child, current price, and the price-history aggregates (drop / rise counts, max drop %) from the union of its children's snapshots.",
    "manual": true,
    "schedules": [
      {
        "cron": "0 * * * *",
        "human": "Every hour (on the hour)"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "batch_size",
        "description": "Properties recomputed per statement",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report straggler + property counts and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "recompute-property-stats",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/recompute_property_stats.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/recompute_property_stats.yml"
  },
  {
    "filename": "refresh_population.yml",
    "name": "Refresh city populations from Wikidata",
    "description": "Pulls the latest population reading for every curated city from Wikidata's public SPARQL endpoint, writes data/csu_population_<year>.csv, and commits it back to the branch. The next run of `Seed curated cities` will pick the CSV up and upsert into `city_population`.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "year",
        "description": "Latest year to accept (e.g. 2024, 2025)",
        "required": false,
        "type": "string",
        "default": "2024",
        "options": null
      },
      {
        "name": "commit",
        "description": "Commit the regenerated CSV back to the branch",
        "required": false,
        "type": "choice",
        "default": "true",
        "options": [
          "true",
          "false"
        ]
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 10,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/refresh_population.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/refresh_population.yml"
  },
  {
    "filename": "scrape.yml",
    "name": "Scraping: Sreality nightly deep run",
    "description": "Deep nightly run. Walks all six category pairs sequentially: byt + dum + komercni  ×  pronajem + prodej",
    "manual": true,
    "schedules": [
      {
        "cron": "0 22 * * *",
        "human": "Daily at 22:00 UTC"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Cap number of listings scraped (blank = all). Applies across the whole run, not per category. Tick 'Skip image download phase' for isolated tests.",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Don't write to the database",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "detail_only",
        "description": "Refetch a single listing by id (skips index)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "no_image_downloads",
        "description": "Skip image download phase",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "max_detail_refetches",
        "description": "Override global detail-refetches-per-run cap (blank = 10000)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "max_detail_refetches_per_category",
        "description": "Override per-category detail-refetches cap (blank = 2000)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "max_image_downloads",
        "description": "Override images-per-run cap (blank = 0 = drain to empty / suspicious-stop)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent workers (blank = 16)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_workers",
        "description": "Override concurrent detail-fetch workers (blank = 4)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_rate",
        "description": "Override global detail-fetch rate cap, req/s (blank = 2.0)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "no_condition_scoring",
        "description": "Skip the condition-scoring phase",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "max_condition_scores",
        "description": "Override condition-scores-per-run cap (blank = 200; ~$3 at cached rate)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 350,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape.yml"
  },
  {
    "filename": "scrape_delta.yml",
    "name": "Scraping: Sreality full index walk (primary, ~hourly)",
    "description": "Primary scrape. Each run walks the COMPLETE index of all six category pairs, so: - newly-listed properties surface (and downstream in the Watchdog feed), and - delisted properties flip to is_active=false — a complete walk is what makes that inference valid (architectural rule #3).",
    "manual": true,
    "schedules": [
      {
        "cron": "0 * * * *",
        "human": "Every hour (on the hour)"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SCRAPE_CHAIN_TOKEN",
      "SUPABASE_DB_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "concurrencyGroup": "sreality-delta-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 35,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_delta.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_delta.yml"
  },
  {
    "filename": "seed_condition_settings.yml",
    "name": "Seed condition settings (Phase B init)",
    "description": "One-shot workflow that populates the two large app_settings rows created by migration 072 — `llm_condition_rubric` and `llm_condition_marker_dictionary` — from the committed JSON files (data/condition_rubric_v1.json + data/condition_markers_curated.json).",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Print sizes and exit without UPDATEing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/seed_condition_settings.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/seed_condition_settings.yml"
  },
  {
    "filename": "seed_curated_cities.yml",
    "name": "Seed curated cities (Phase QUAL init)",
    "description": "One-shot workflow that geocodes the 206 cities in data/obce_v_datech_2025.csv via Mapy.cz, then writes them into curated_cities + city_index_definitions + city_index_revisions + city_index_values (+ city_population if the CSV is present).",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Plan only — geocode, but skip DB writes",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      },
      {
        "name": "commit_geocodes",
        "description": "Commit data/curated_cities_geocoded.json back to the branch",
        "required": false,
        "type": "choice",
        "default": "true",
        "options": [
          "true",
          "false"
        ]
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 15,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/seed_curated_cities.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/seed_curated_cities.yml"
  },
  {
    "filename": "smoke_agent.yml",
    "name": "Agent smoke test",
    "description": "Manual invocation only. Runs scripts/smoke_agent.py against the real Supabase DB and a real LLM provider. Picks a recent Prague 2+kk rental by default; --sreality-id overrides. Real LLM credits are spent — typically under $0.10 per run.",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "provider",
        "description": "LLM provider (anthropic or gemini)",
        "required": true,
        "type": "choice",
        "default": "anthropic",
        "options": [
          "anthropic",
          "gemini"
        ]
      },
      {
        "name": "sreality_id",
        "description": "Specific listing id to estimate (leave blank to pick a recent Prague 2+kk)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "skill",
        "description": "Skill row name",
        "required": false,
        "type": "string",
        "default": "rental_estimator_v1",
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "GEMINI_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/smoke_agent.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/smoke_agent.yml"
  },
  {
    "filename": "test.yml",
    "name": "tests",
    "description": "CI test suite, runs on every push and pull request. Two parallel jobs: a Python job (verifies the filter-registry and workflow-docs codegen are fresh, then runs pytest) and a frontend job (TypeScript type-check + vitest pure-function tests). This is the build gate for every branch.",
    "manual": false,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": null,
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/test.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/test.yml"
  }
];
