// AUTOGENERATED — DO NOT EDIT.
// Source of truth: the .github/workflows/*.yml files.
// Regenerate with: python scripts/generate_workflow_docs.py
//
// CI runs `--check` and fails on drift, so adding, removing, or editing
// a workflow must be paired with a fresh regen in the same commit. The
// per-workflow `description` is the first paragraph of the leading
// comment block at the top of each YAML file.

export interface WorkflowInput {
  name: string;
  description: string;
  required: boolean;
  type: string;
  default: string | null;
  options: string[] | null;
}

export interface WorkflowSchedule {
  cron: string;
  human: string;
}

export interface WorkflowDoc {
  filename: string;
  name: string;
  description: string;
  portal: string | null;
  manual: boolean;
  schedules: WorkflowSchedule[];
  onPush: boolean;
  onPullRequest: boolean;
  paths: string[] | null;
  inputs: WorkflowInput[];
  secrets: string[];
  concurrencyGroup: string | null;
  cancelInProgress: boolean | null;
  timeoutMinutes: number | null;
  permissions: string | null;
  runsUrl: string;
  sourceUrl: string;
}

export const WORKFLOW_DOCS: WorkflowDoc[] = [
  {
    "filename": "aggregate_condition_markers.yml",
    "name": "Dev: aggregate condition markers (one-off Phase A bootstrap)",
    "description": "Runs scripts/aggregate_condition_markers.py against the live `listing_marker_extractions` rows to produce data/condition_markers_v1.json, then commits the JSON back to the running branch so the operator can review it in the PR diff.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "output_path",
        "description": "Output JSON path inside the repo",
        "required": true,
        "type": "string",
        "default": "data/condition_markers_v1.json",
        "options": null
      },
      {
        "name": "min_cluster_count",
        "description": "Drop clusters whose total count is below this",
        "required": true,
        "type": "string",
        "default": "3",
        "options": null
      },
      {
        "name": "similarity_threshold",
        "description": "difflib ratio merge threshold (0.0-1.0)",
        "required": true,
        "type": "string",
        "default": "0.85",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 15,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/aggregate_condition_markers.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/aggregate_condition_markers.yml"
  },
  {
    "filename": "bazos_detail_drain.yml",
    "name": "Scraping: Bazos detail drain",
    "description": "The slow half of the bazos cadence split (architectural rule #19, like sreality/idnes). Claims a bounded slice of listing_detail_queue (source='bazos', enqueued by bazos_index_walk.yml), fetches each ad's detail page on a rate-limited worker pool, parses it (the real category comes off the page breadcrumb), and ingests via db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching). Records run_type='detail' (index_pages=0). The drain records image-URL rows; the shared images.yml job downloads the bytes to R2.",
    "portal": "bazos",
    "manual": true,
    "schedules": [
      {
        "cron": "45 * * * *",
        "human": "Every hour at :45"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_seconds",
        "description": "wall-clock drain budget, finalizes cleanly before timeout (blank = 2400 = 40 min)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "hard cap on ads claimed this run (blank = none; the time budget governs)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "workers",
        "description": "concurrent detail-fetch workers (blank = 2)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "rate",
        "description": "global detail-fetch rate cap, req/s (blank = 0.6)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bazos-detail-drain",
    "cancelInProgress": false,
    "timeoutMinutes": 50,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/bazos_detail_drain.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/bazos_detail_drain.yml"
  },
  {
    "filename": "bazos_index_walk.yml",
    "name": "Scraping: Bazos index walk",
    "description": "The fast half of the bazos cadence split (architectural rule #19, like sreality/idnes). Walks the ENTIRE index of every configured scope (no --max-pages), touch_listings bumps last_seen on still-listed ads, mark_inactive flips delisted ones under the completeness guard (source-scoped, throttled to once per 12h), and new/price-changed ids are enqueued into listing_detail_queue (source='bazos'). No detail fetch — the drain (bazos_detail_drain.yml) consumes the queue. Records run_type='index'.",
    "portal": "bazos",
    "manual": true,
    "schedules": [
      {
        "cron": "0 */6 * * *",
        "human": "Every 6 hours"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "sale_type",
        "description": "prodam (sale) or pronajmu (rent); blank = every configured scope",
        "required": false,
        "type": "choice",
        "default": "",
        "options": [
          "",
          "prodam",
          "pronajmu"
        ]
      },
      {
        "name": "category",
        "description": "bazos category segment; blank = every configured scope",
        "required": false,
        "type": "choice",
        "default": "",
        "options": [
          "",
          "byt",
          "dum",
          "chata",
          "restaurace",
          "kancelar",
          "prostory",
          "sklad"
        ]
      },
      {
        "name": "locality",
        "description": "locality filter (e.g. Praha); blank = nationwide",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "radius_km",
        "description": "radius around locality in km (blank = none)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_pages",
        "description": "cap index pages per scope (ad-hoc partial; suppresses mark_inactive). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bazos-index-walk",
    "cancelInProgress": false,
    "timeoutMinutes": 75,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/bazos_index_walk.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/bazos_index_walk.yml"
  },
  {
    "filename": "build-extension.yml",
    "name": "CI: build Chrome extension",
    "description": "Builds the chrome-extension/ bundle and uploads dist/ as a workflow artifact you can download from the Actions tab. Keeps the build off the operator's laptop (no local Node install needed).",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/build-extension.yml",
      "chrome-extension/**"
    ],
    "inputs": [],
    "secrets": [
      "EXT_API_BASE_URL",
      "EXT_API_TOKEN"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": null,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/build-extension.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/build-extension.yml"
  },
  {
    "filename": "compare_condition_models.yml",
    "name": "Scoring: Condition model A/B (Haiku vs Sonnet)",
    "description": "Read-only validation harness for a cheaper condition-scoring model. For a sample of listings that already have a baseline-model score on their latest snapshot, it re-runs the SAME scoring request through a candidate model and reports per-axis agreement (exact / within-1 / mean abs diff / bias) plus the candidate vs baseline cost ratio.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "candidate_model",
        "description": "Cheaper model to validate (e.g. claude-haiku-4-5)",
        "required": true,
        "type": "string",
        "default": "claude-haiku-4-5",
        "options": null
      },
      {
        "name": "baseline_model",
        "description": "Model whose existing scores are the comparison baseline",
        "required": true,
        "type": "string",
        "default": "claude-sonnet-4-5",
        "options": null
      },
      {
        "name": "limit",
        "description": "Number of already-scored listings to re-score with the candidate",
        "required": true,
        "type": "string",
        "default": "40",
        "options": null
      },
      {
        "name": "region_ids",
        "description": "Comma-separated locality_region_id list (empty = all regions)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 = text-only, matches production scoring)",
        "required": true,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop once the candidate-model spend for this run crosses this (USD)",
        "required": true,
        "type": "string",
        "default": "2",
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 20,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/compare_condition_models.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/compare_condition_models.yml"
  },
  {
    "filename": "compute_image_phash.yml",
    "name": "Compute image pHash (multi-portal dedup)",
    "description": "Backfills images.phash (a 64-bit perceptual dHash per stored image) for the Tier-2 dedup sweep's cheap image corroborator. Downloads stored bytes from R2, hashes them, writes images.phash. Idempotent + resumable; a no-op if R2 env vars are missing.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "20 */6 * * *",
        "human": "Every 6 hours at :20"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Max images hashed per run",
        "required": false,
        "type": "string",
        "default": "5000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report the pending count and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "compute-image-phash",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/compute_image_phash.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/compute_image_phash.yml"
  },
  {
    "filename": "condition_score_batches.yml",
    "name": "Scraping: Sreality condition scoring (batch API)",
    "description": "Phase 1.8b — async condition scoring via the Anthropic Message Batches API (50% cheaper than the synchronous condition_scores.yml job). Two modes, selected by the `mode` input:",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "5 */3 * * *",
        "human": "Every 3 hours at :05"
      },
      {
        "cron": "35 * * * *",
        "human": "Every hour at :35"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "mode",
        "description": "submit a new batch, or ingest completed ones",
        "required": true,
        "type": "choice",
        "default": "ingest",
        "options": [
          "ingest",
          "submit"
        ]
      },
      {
        "name": "region_ids",
        "description": "[submit] Comma-separated locality_region_id list (empty = no filter)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "limit",
        "description": "[submit] Max listings to put in the batch",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "n_images",
        "description": "[submit] Images per listing (0 = text-only, matches production)",
        "required": false,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "max_age_days",
        "description": "[submit] Only listings seen within this many days (0 = no filter)",
        "required": false,
        "type": "string",
        "default": "30",
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "condition-score-batches",
    "cancelInProgress": false,
    "timeoutMinutes": 60,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/condition_score_batches.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/condition_score_batches.yml"
  },
  {
    "filename": "condition_scores.yml",
    "name": "Scraping: Sreality condition scoring (hourly + manual backfill)",
    "description": "Decoupled condition-scoring job. Scores building/apartment condition (1..5) for active listings whose latest snapshot doesn't yet have a row in `listing_condition_scores`, writing both the cache row AND the two listings.*_condition_level columns in one transaction per listing (autocommit — every successful score commits independently, so a timeout or cancel preserves the rows already done). Resumable: scored listings drop out of the next selection.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "region_ids",
        "description": "Comma-separated locality_region_id list (empty = no region filter)",
        "required": false,
        "type": "string",
        "default": "10,11,2,13",
        "options": null
      },
      {
        "name": "limit",
        "description": "Maximum number of listings to score in this run",
        "required": true,
        "type": "string",
        "default": "500",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 disables vision; default 0 matches discovery)",
        "required": true,
        "type": "string",
        "default": "0",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "10",
        "options": null
      },
      {
        "name": "max_age_days",
        "description": "Only score listings whose last_seen_at is within this many days (0 = no freshness filter)",
        "required": true,
        "type": "string",
        "default": "30",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Print first 20 pending IDs and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "condition-scoring",
    "cancelInProgress": false,
    "timeoutMinutes": 55,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/condition_scores.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/condition_scores.yml"
  },
  {
    "filename": "dedup_engine.yml",
    "name": "Dedup engine (street + disposition)",
    "description": "Street + disposition keyed dedup engine. Groups listings that share a street and disposition into one real-world property, autonomously. Replaces the old geo-proximity Tier-2 sweep. Rules: (A) only listings with BOTH a street and a disposition are eligible; (B) same street + house number + disposition + floor auto-merges (with a 5% area guard); (C) same street + disposition with no contradicting floor/area/house-number becomes a visual candidate; (D) the visual layer confirms — >=2 near-identical interior photos (pHash), else a room-aware forensic comparison stopping at the first High verdict — and merges on confirmation; (E) everything else is queued for the operator's /dedup page.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "45 4 * * *",
        "human": "Daily at 04:45 UTC"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pairs",
        "description": "Max visual candidate pairs examined per run",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "max_vision_calls",
        "description": "Cap forensic vision calls per run (0 = pHash-only)",
        "required": false,
        "type": "string",
        "default": "200",
        "options": null
      },
      {
        "name": "max_room_attempts",
        "description": "Max like-room forensic comparisons per candidate pair",
        "required": false,
        "type": "string",
        "default": "4",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report eligible counts + street groups and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "GEMINI_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "dedup-engine",
    "cancelInProgress": false,
    "timeoutMinutes": 45,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/dedup_engine.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/dedup_engine.yml"
  },
  {
    "filename": "detail_drain.yml",
    "name": "Scraping: Sreality detail drain (Phase 2)",
    "description": "The slow half of the Phase-2 cadence split. Claims a bounded slice of listing_detail_queue (enqueued by index_walk.yml), fetches each listing's detail on a rate-limited worker pool, and writes them in batches via the set-based write_detail_batch (one transaction per ~100 listings) — targeting ~0.1-0.2 s/listing versus the ~1.5 s of the legacy per-listing write. New listings land with property_id NULL; the Tier-1 matcher is deferred to the recompute_property_stats straggler-attach phase.",
    "portal": "sreality",
    "manual": true,
    "schedules": [
      {
        "cron": "*/15 * * * *",
        "human": "Every 15 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_detail_refetches",
        "description": "Cap listings claimed + fetched this run (blank = 12000)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_workers",
        "description": "Concurrent detail-fetch workers (blank = 8)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_rate",
        "description": "Global detail-fetch rate cap, req/s (blank = 6.0)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report the claimable queue depth and exit without claiming",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_SESSION_URL",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-detail-drain",
    "cancelInProgress": false,
    "timeoutMinutes": 50,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/detail_drain.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/detail_drain.yml"
  },
  {
    "filename": "discover_condition_markers.yml",
    "name": "Dev: discover condition markers (one-off Phase A bootstrap)",
    "description": "One-off Phase A driver for the building/apartment condition-scoring feature. Runs scripts/discover_condition_markers.py against the real Supabase DB and the Anthropic API to mine Czech condition markers from a stratified sample of listings.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Maximum number of listings to extract markers for",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "n_images",
        "description": "Images per listing (0 disables vision; default 5)",
        "required": true,
        "type": "string",
        "default": "5",
        "options": null
      },
      {
        "name": "per_cell_cap",
        "description": "Max picks per stratification cell",
        "required": true,
        "type": "string",
        "default": "6",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "80",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Print sample and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 180,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/discover_condition_markers.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/discover_condition_markers.yml"
  },
  {
    "filename": "enrich_bazos.yml",
    "name": "Scraping: Bazos description enrichment (LLM, every 6h + manual)",
    "description": "Decoupled enrichment job. bazos listings carry no structured floor / amenities / condition / building_type / energy — only price, area, disposition, coords, and the seller's free text. This reads the description of active listings whose latest snapshot isn't yet enriched, extracts those typed fields with a cheap model (Haiku 4.5), caches the extraction in listing_description_enrichments, and fills ONLY the currently-NULL listings columns (the deterministic HTML-parsed price/area/disposition are never overwritten). Resumable: enriched snapshots drop out of the next selection.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "20 */6 * * *",
        "human": "Every 6 hours at :20"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "source",
        "description": "Portal source to enrich (description-only portals)",
        "required": true,
        "type": "string",
        "default": "bazos",
        "options": null
      },
      {
        "name": "limit",
        "description": "Maximum number of listings to enrich in this run",
        "required": true,
        "type": "string",
        "default": "1000",
        "options": null
      },
      {
        "name": "max_cost_usd",
        "description": "Stop early when this run's LLM cost exceeds this cap (USD)",
        "required": true,
        "type": "string",
        "default": "10",
        "options": null
      },
      {
        "name": "model",
        "description": "Anthropic model id (blank = claude-haiku-4-5)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Count pending listings and exit without calling the LLM",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bazos-enrichment",
    "cancelInProgress": false,
    "timeoutMinutes": 55,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/enrich_bazos.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/enrich_bazos.yml"
  },
  {
    "filename": "fetch-fixtures.yml",
    "name": "Fixtures: source HTML (anonymized)",
    "description": "Manual trigger only. Fetches each listing URL, runs the anonymization in scripts/fetch_and_anonymize_fixtures.py, and commits the resulting fixtures to the current branch. Operator runs this once per source refresh; tests then read the saved files instead of hitting the internet.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "bezrealitky_url",
        "description": "bezrealitky.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://www.bezrealitky.cz/nemovitosti-byty-domy/547214-nabidka-pronajem-bytu-pod-harfou-hlavni-mesto-praha",
        "options": null
      },
      {
        "name": "idnes_url",
        "description": "reality.idnes.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://reality.idnes.cz/detail/pronajem/byt/brno-veveri/69f8c898e58c5ab7d70f3505/",
        "options": null
      },
      {
        "name": "remax_url",
        "description": "remax-czech.cz listing URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://www.remax-czech.cz/reality/detail/438735/pronajem-bytu-1-kk-v-osobnim-vlastnictvi-31-m2-praha-8-liben",
        "options": null
      },
      {
        "name": "bazos_index_url",
        "description": "reality.bazos.cz search/index URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "https://reality.bazos.cz/prodam/byt/",
        "options": null
      },
      {
        "name": "bazos_detail_url",
        "description": "reality.bazos.cz single-listing detail URL (leave blank to skip)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch-fixtures.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch-fixtures.yml"
  },
  {
    "filename": "fetch_rent_map.yml",
    "name": "Jobs: fetch MF rent map (monthly)",
    "description": "Auto-grab the Ministry of Finance \"Cenová mapa nájemného\" (rent price map) from the MF infografika page, parse it, and append a new rent_map revision — unless the file's sha256 already exists (then it's a no-op). The MF data updates 4×/year (published within 45 days of each quarter end), so a monthly cron mostly no-ops and catches the new release within ~30 days. The same data also lands via manual upload from the Settings page; both share api.rent_map.ingest_bytes, so the latest revision always wins.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "0 3 5 * *",
        "human": "0 3 5 * *"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "source_url",
        "description": "Override the MF page URL to scrape the XLSX link from",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Parse + report counts without writing a revision",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "rent-map-fetch",
    "cancelInProgress": false,
    "timeoutMinutes": 15,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch_rent_map.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch_rent_map.yml"
  },
  {
    "filename": "fetch_sreality_fixtures.yml",
    "name": "Fixtures: sreality v1 JSON",
    "description": "Manual trigger only. Fetches a real search response + one real detail response from a GitHub runner IP (this repo's dev sandbox is 403'd by sreality), scrubs emails/phone numbers, and commits the result as tests/fixtures/sample_search.json + sample_listing.json on the current branch. The live /api/v1/estates API is snake_case (id key `hash_id`, detail wrapped under `result`); these fixtures pin the true shape so the parser tests guard reality instead of the HAR-derived camelCase guess.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "category_main",
        "description": "category_main_cb (1=byt, 2=dum, 4=komercni)",
        "required": false,
        "type": "string",
        "default": "1",
        "options": null
      },
      {
        "name": "category_type",
        "description": "category_type_cb (1=prodej, 2=pronajem)",
        "required": false,
        "type": "string",
        "default": "1",
        "options": null
      },
      {
        "name": "detail_id",
        "description": "Override detail hash_id (blank = first search result)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/fetch_sreality_fixtures.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/fetch_sreality_fixtures.yml"
  },
  {
    "filename": "frontend-build.yml",
    "name": "CI: frontend build",
    "description": "Builds the frontend/ Vite SPA on every push or pull request that touches frontend code, to catch build/type errors before deploy. Type-checks, builds the production bundle, and reports gzipped chunk sizes (warning if the initial JS chunk exceeds the 500 kB budget). Does not deploy.",
    "portal": null,
    "manual": false,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/frontend-build.yml",
      "frontend/**"
    ],
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": null,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/frontend-build.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/frontend-build.yml"
  },
  {
    "filename": "idnes_detail_drain.yml",
    "name": "Scraping: iDNES Reality detail drain",
    "description": "The slow half of the iDNES cadence split (architectural rule #19, like sreality). Claims a bounded slice of listing_detail_queue (source='idnes', enqueued by idnes_index_walk.yml), fetches each listing page on a rate-limited worker pool, parses it to a ScrapedListing, and ingests via db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching). The per-listing category is derived from its detail URL. Records run_type='detail' (index_pages=0). The drain records image-URL rows; the shared images.yml job downloads the bytes to R2.",
    "portal": "idnes",
    "manual": true,
    "schedules": [
      {
        "cron": "30 * * * *",
        "human": "Every hour at :30"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_seconds",
        "description": "wall-clock drain budget, finalizes cleanly before timeout (blank = 2400 = 40 min)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "hard cap on listings claimed this run (blank = none; the time budget governs)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "workers",
        "description": "concurrent detail-fetch workers (blank = 8)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "rate",
        "description": "global detail-fetch rate cap, req/s (blank = 4.0)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "idnes-detail-drain",
    "cancelInProgress": false,
    "timeoutMinutes": 50,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/idnes_detail_drain.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/idnes_detail_drain.yml"
  },
  {
    "filename": "idnes_index_walk.yml",
    "name": "Scraping: iDNES Reality index walk",
    "description": "The fast half of the iDNES cadence split (architectural rule #19, like sreality). Walks the ENTIRE index of every configured category (no --max-pages), touch_listings bumps last_seen on still-listed ids, mark_inactive flips delisted ones under the completeness guard (source-scoped), and new/price-changed ids are enqueued into listing_detail_queue (source='idnes'). No detail fetch — the drain (idnes_detail_drain.yml) consumes the queue. Records run_type='index'.",
    "portal": "idnes",
    "manual": true,
    "schedules": [
      {
        "cron": "15 */6 * * *",
        "human": "Every 6 hours at :15"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap index pages per category (ad-hoc partial; suppresses mark_inactive). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "idnes-index-walk",
    "cancelInProgress": false,
    "timeoutMinutes": 75,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/idnes_index_walk.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/idnes_index_walk.yml"
  },
  {
    "filename": "images.yml",
    "name": "Scraping: image backlog drain (sharded)",
    "description": "THE backlog image-download workflow. Images are fully decoupled from every portal's crawl (the crawls only record image-URL rows; this job uploads the bytes to R2), so this is the owner of the deep backlog across ALL portals (sreality, idnes, bazos, bezrealitky, maxima, mmreality). Source-agnostic.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "0 */2 * * *",
        "human": "Every 2 hours"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_image_downloads",
        "description": "Override per-shard images-per-run cap (blank = 18000; 0 = drain to empty / suspicious-stop)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent workers per shard (blank = 32)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "images_active_only",
        "description": "Restrict to active listings only. Default false: drain the full backlog incl. inactive (the fresh fast lane already covers new actives).",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 110,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/images.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/images.yml"
  },
  {
    "filename": "images_fresh.yml",
    "name": "Scraping: fresh-listing image fast lane",
    "description": "Low-latency image fetch for the NEWEST active listings across ALL portals, so a freshly-scraped card renders a photo within minutes instead of waiting for the 2-hourly sharded backlog drain (images.yml). The frontend can only show an image once its bytes are in R2 (storage_path set) — original portal URLs are hotlink/expiry-protected — so racing those URLs on fresh listings is also what prevents the image loss we already saw (~43k+ sreality images lost to expiry).",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "*/15 * * * *",
        "human": "Every 15 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_image_downloads",
        "description": "Override per-run cap (blank = 2500)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent workers (blank = 32)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SCRAPE_CHAIN_TOKEN",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "images-fresh",
    "cancelInProgress": false,
    "timeoutMinutes": 20,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/images_fresh.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/images_fresh.yml"
  },
  {
    "filename": "index_walk.yml",
    "name": "Scraping: Sreality index walk (Phase 2)",
    "description": "The fast half of the Phase-2 cadence split. Walks the COMPLETE index of all six category pairs, bumps last_seen on still-listed ids (touch), flips delisted ones to is_active=false (mark_inactive, under the completeness guard), and enqueues new + price-changed ids into listing_detail_queue for the asynchronous detail-drain. It does NO detail fetching, so it finishes in minutes and delistings surface fast — decoupled from the slow per-listing write that used to drag it.",
    "portal": "sreality",
    "manual": true,
    "schedules": [
      {
        "cron": "*/15 * * * *",
        "human": "Every 15 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Walk the index and log enqueue intent, but write nothing",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-index-walk",
    "cancelInProgress": false,
    "timeoutMinutes": 25,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/index_walk.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/index_walk.yml"
  },
  {
    "filename": "ingest_boundaries.yml",
    "name": "Data: ingest admin boundaries",
    "description": "Loads ČÚZK RÚIAN administrative-unit polygons (kraj / okres / obec / KÚ) into the admin_boundaries table. Manual-only; boundaries change rarely (a few municipal mergers / cadastral re-alignments per year), so there is no cron. Re-run when ČÚZK publishes a notable update or when the operator wants to bring in newly-created units.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "source_url",
        "description": "RÚIAN SHP zip URL (from ČÚZK ATOM feed)",
        "required": true,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "levels",
        "description": "Levels to load (comma-separated). Default: all four.",
        "required": false,
        "type": "string",
        "default": "kraj,okres,obec,ku",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Parse and validate only; do not write to DB.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "skip_spatial_join",
        "description": "Skip the listings -> sreality_id population step.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "no_truncate",
        "description": "Skip TRUNCATE; upsert into existing rows instead.",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/ingest_boundaries.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/ingest_boundaries.yml"
  },
  {
    "filename": "llm_health.yml",
    "name": "Monitoring: LLM pipeline liveness",
    "description": "Goes red (→ GitHub notifies the operator on a failed scheduled run) when the LLM pipeline looks dead: no `llm_calls` rows for several hours while there is pending condition-scoring work. Catches the silent failure mode where the Anthropic account runs out of credits / the key breaks and the scorers swallow per-listing errors, staying green while scoring nothing (this went unnoticed for ~8h on 2026-06-04).",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "15 * * * *",
        "human": "Every hour at :15"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "llm-health",
    "cancelInProgress": false,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/llm_health.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/llm_health.yml"
  },
  {
    "filename": "load_obec_population.yml",
    "name": "Jobs: load obec population (manual)",
    "description": "Load ČSÚ municipality population into admin_boundaries.population for EVERY obec (not just the 206 curated cities). Reads the committed DataStat export data/csu_population.json (OBY02AT02 — download from https://data.csu.gov.cz/datastat/data/VYBER/OBY02AT02). Idempotent: only changed rows are written. Dispatch this after committing a refreshed export. This is the population source the \"within X km of a municipality with population > N\" proximity filter reads.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "load-obec-population",
    "cancelInProgress": false,
    "timeoutMinutes": 15,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/load_obec_population.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/load_obec_population.yml"
  },
  {
    "filename": "migrations.yml",
    "name": "CI: migration smoke-test",
    "description": "Applies the full migrations/ chain (001 -> latest) to a throwaway Postgres + PostGIS container whenever anything under migrations/ changes, catching a migration that does not apply cleanly before it reaches the production Supabase database (there is no staging DB). It pre-creates the Supabase roles the migrations GRANT to (anon / authenticated / service_role) and the pg_trgm extension migrations 067 / 074 rely on, applies every *.sql in numeric order, then runs a small sanity query. Hermetic: no secrets, never touches production.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": [
      ".github/workflows/migrations.yml",
      "migrations/**",
      "scripts/ci_db_bootstrap.sql"
    ],
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 10,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/migrations.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/migrations.yml"
  },
  {
    "filename": "property_maintenance.yml",
    "name": "Jobs: property maintenance (incremental)",
    "description": "Phase 3 of the scaling roadmap: real-time properties. This is the FAST, FREQUENT half of property maintenance — the dirty-set incremental pass. It runs scripts/recompute_property_stats --incremental, which:",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "*/5 * * * *",
        "human": "Every 5 minutes"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "batch_size",
        "description": "Properties recomputed per statement",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report straggler + dirty + property counts and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-property-maintenance",
    "cancelInProgress": false,
    "timeoutMinutes": 10,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/property_maintenance.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/property_maintenance.yml"
  },
  {
    "filename": "recompute_city_proximity.yml",
    "name": "Jobs: recompute city proximity (hourly)",
    "description": "Recompute properties.home_obec_pop + near_{pop,jobs,youth,overall}_{5,15}km (migration 142) so the Browse / Watchdog city-proximity + Min Population filters read precomputed indexed columns instead of a per-request spatial RPC. Incremental hourly run fills newly-ingested properties within the hour; the same function rebuilds everything after a population / city-index load.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "40 * * * *",
        "human": "Every hour at :40"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "full",
        "description": "Rebuild every property (not just new ones)",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "recompute-city-proximity",
    "cancelInProgress": false,
    "timeoutMinutes": 25,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/recompute_city_proximity.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/recompute_city_proximity.yml"
  },
  {
    "filename": "recompute_mf_yields.yml",
    "name": "Jobs: recompute MF gross yields (hourly)",
    "description": "Recompute listings.mf_gross_yield_pct (MF Cenová mapa reference rent / asking price) for every sale apartment. The yield shifts when a listing's price changes (scrape) or the rent map updates (quarterly), so a cheap, idempotent set-based recompute runs hourly to keep new + re-priced listings filterable in Browse within the hour. The same function also runs after each rent-map ingest (scripts.fetch_rent_map). Only changed rows are written.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "25 * * * *",
        "human": "Every hour at :25"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "recompute-mf-yields",
    "cancelInProgress": false,
    "timeoutMinutes": 15,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/recompute_mf_yields.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/recompute_mf_yields.yml"
  },
  {
    "filename": "recompute_property_stats.yml",
    "name": "Jobs: recompute property stats (daily full reconcile)",
    "description": "DAILY FULL SWEEP for the canonical `properties` parent. Attaches any straggler unlinked listings (incl. the one-time native-id backfill), then recomputes EVERY property's is_active rollup, source / site counts, first/last-seen span, representative child, current price, and the price-history aggregates (drop / rise counts, max drop %) from the union of its children's snapshots. Finally it clears the dirty_properties queue (everything was just recomputed).",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "15 4 * * *",
        "human": "Daily at 04:15 UTC"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "batch_size",
        "description": "Properties recomputed per statement",
        "required": true,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report straggler + dirty + property counts and exit without writing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "sreality-property-maintenance",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/recompute_property_stats.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/recompute_property_stats.yml"
  },
  {
    "filename": "refresh_population.yml",
    "name": "Data: refresh city populations (Wikidata)",
    "description": "FALLBACK SOURCE. The preferred population source is now the official ČSÚ DataStat export \"Počet obyvatel v obcích k 1. 1.\" — download the JSON from https://data.csu.gov.cz/datastat/data/VYBER/OBY02AT02, commit it to data/csu_population.json, and run \"Data: seed curated cities\" (which ingests the JSON directly). Use this Wikidata fetcher only when you can't get the official file.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "year",
        "description": "Latest year to accept (e.g. 2024, 2025)",
        "required": false,
        "type": "string",
        "default": "2024",
        "options": null
      },
      {
        "name": "commit",
        "description": "Commit the regenerated CSV back to the branch",
        "required": false,
        "type": "choice",
        "default": "true",
        "options": [
          "true",
          "false"
        ]
      }
    ],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 10,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/refresh_population.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/refresh_population.yml"
  },
  {
    "filename": "refresh_stale_images.yml",
    "name": "Jobs: refresh stale image URLs",
    "description": "Re-opens active listings whose photos aren't in R2 yet so their (possibly rotated) source image URLs get refreshed. Portals rotate image CDN URLs over weeks; a listing whose images the newest-first backfill never reached before its URLs rotated is stuck — the stored URL 404s, the frontend fallback can't load it, and the image downloader can't fetch it. This sweep (scripts.refresh_stale_image_urls) re-enqueues such listings into the source-generic listing_detail_queue; the detail drain re-fetches them, record_images repoints each not-yet-stored image's URL to the current one, and the image backfill (images.yml) then stores the bytes.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "20 */6 * * *",
        "human": "Every 6 hours at :20"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Max listings to re-enqueue this run",
        "required": false,
        "type": "string",
        "default": "5000",
        "options": null
      },
      {
        "name": "min_age",
        "description": "Only sweep listings older than this Postgres interval (unless they have a confirmed-stale image)",
        "required": false,
        "type": "string",
        "default": "3 days",
        "options": null
      },
      {
        "name": "cooldown",
        "description": "Per-listing cooldown — skip listings re-enqueued within this interval",
        "required": false,
        "type": "string",
        "default": "14 days",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Report counts and exit without enqueuing",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "refresh-stale-images",
    "cancelInProgress": false,
    "timeoutMinutes": 20,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/refresh_stale_images.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/refresh_stale_images.yml"
  },
  {
    "filename": "scrape.yml",
    "name": "Scraping: Sreality combined walk (Phase-2 fallback, dispatch-only)",
    "description": "DISPATCH-ONLY FALLBACK as of Phase 2. The hourly cron was removed: the live pipeline is now the cadence split — index_walk.yml (fast, frequent, marks delistings + enqueues) feeds detail_drain.yml (async, batched writes). This combined index+detail walk (_run_full) is kept intact as the instant revert: if the split misbehaves, re-add `schedule: - cron: \"0 * * * *\"` here and disable the two new crons — no code change, the proven pipeline is back. It also remains the way to run an ad-hoc full walk by hand.",
    "portal": "sreality",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "limit",
        "description": "Cap number of listings scraped (blank = all). Applies across the whole run, not per category. A capped run records run_type='delta' and skips mark_inactive.",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Don't write to the database",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "detail_only",
        "description": "Refetch a single listing by id (skips index)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "no_image_downloads",
        "description": "Skip image download phase",
        "required": false,
        "type": "boolean",
        "default": "false",
        "options": null
      },
      {
        "name": "max_detail_refetches",
        "description": "Override global detail-refetches-per-run cap (blank = 4000)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "max_detail_refetches_per_category",
        "description": "Override per-category detail-refetches cap (blank = 1200)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "max_image_downloads",
        "description": "Override images-per-run cap (blank = 0 = drain active to empty / suspicious-stop)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "image_workers",
        "description": "Override concurrent image workers (blank = 16)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_workers",
        "description": "Override concurrent detail-fetch workers (blank = 8)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      },
      {
        "name": "detail_rate",
        "description": "Override global detail-fetch rate cap, req/s (blank = 6.0)",
        "required": false,
        "type": "string",
        "default": null,
        "options": null
      }
    ],
    "secrets": [
      "R2_ACCESS_KEY_ID",
      "R2_ACCOUNT_ID",
      "R2_BUCKET_NAME",
      "R2_SECRET_ACCESS_KEY",
      "SCRAPE_CHAIN_TOKEN",
      "SUPABASE_DB_SESSION_URL",
      "SUPABASE_DB_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "concurrencyGroup": "sreality-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 90,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape.yml"
  },
  {
    "filename": "scrape_bazos.yml",
    "name": "Scraping: Bazos crawler combined walk (fallback)",
    "description": "DISPATCH-ONLY combined index+detail fallback for reality.bazos.cz, mirroring sreality's scrape.yml and idnes's scrape_idnes.yml. The scheduled pipeline is the cadence SPLIT — the full bazos_index_walk.yml (walk + mark_inactive + enqueue) feeds the bounded bazos_detail_drain.yml — because bazos now walks 14 nationwide scopes (~1500 index pages, ~50 min) and a single combined run can't do both inside one job (the full index eats the window, starving the drain).",
    "portal": "bazos",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "sale_type",
        "description": "prodam (sale) or pronajmu (rent); blank = every configured scope",
        "required": false,
        "type": "choice",
        "default": "",
        "options": [
          "",
          "prodam",
          "pronajmu"
        ]
      },
      {
        "name": "category",
        "description": "bazos category segment; blank = every configured scope",
        "required": false,
        "type": "choice",
        "default": "",
        "options": [
          "",
          "byt",
          "dum",
          "chata",
          "restaurace",
          "kancelar",
          "prostory",
          "sklad"
        ]
      },
      {
        "name": "locality",
        "description": "locality filter (e.g. Praha); blank = nationwide",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "radius_km",
        "description": "radius around locality in km (blank = none)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_pages",
        "description": "cap index pages per scope (blank = full walk)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run (blank = drain the queue)",
        "required": false,
        "type": "string",
        "default": "400",
        "options": null
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bazos-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 50,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_bazos.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_bazos.yml"
  },
  {
    "filename": "scrape_bezrealitky.yml",
    "name": "Scraping: Bezrealitky scraper (pilot)",
    "description": "Scheduled (every 6h) + manual scraper for bezrealitky.cz on the shared portal framework. Bezrealitky is a JSON-API portal (public GraphQL at api.bezrealitky.cz) like sreality: the index walk pages listAdverts and enqueues new/price-changed ids into listing_detail_queue, then the detail drain fetches advert(id), parses to a ScrapedListing, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching).",
    "portal": "bezrealitky",
    "manual": true,
    "schedules": [
      {
        "cron": "45 */6 * * *",
        "human": "Every 6 hours at :45"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap index pages per category (ad-hoc partial; suppresses mark_inactive). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "2.0",
        "options": null
      },
      {
        "name": "workers",
        "description": "detail-fetch workers (concurrency; raise for a one-time backfill)",
        "required": false,
        "type": "string",
        "default": "8",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "bezrealitky-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_bezrealitky.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_bezrealitky.yml"
  },
  {
    "filename": "scrape_idnes.yml",
    "name": "Scraping: iDNES Reality combined walk (fallback)",
    "description": "DISPATCH-ONLY combined index+detail fallback for reality.idnes.cz, mirroring sreality's scrape.yml. The scheduled pipeline is the cadence SPLIT — the fast idnes_index_walk.yml (full walk + mark_inactive + enqueue) feeds the bounded idnes_detail_drain.yml — because iDNES is large (~2400 index pages, ~60k listings) and a single combined run can't do both inside one job (the full index eats the window, starving the drain).",
    "portal": "idnes",
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap index pages per category (ad-hoc partial; suppresses mark_inactive). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run",
        "required": false,
        "type": "string",
        "default": "6000",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "3.0",
        "options": null
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "idnes-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 55,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_idnes.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_idnes.yml"
  },
  {
    "filename": "scrape_maxima.yml",
    "name": "Scraping: Maxima Reality scraper (pilot)",
    "description": "Scheduled (every 6h) + manual scraper for nemovitosti.maxima.cz on the shared portal framework. Maxima is a single real-estate agency that publishes its whole catalogue (~220 listings) as one server-rendered WordPress index (no JSON API, no per-category URL): the index walk pages the catalogue and enqueues new/price-changed ids into listing_detail_queue, then the detail drain fetches each /nemovitosti/{id}/ page, parses to a ScrapedListing, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching).",
    "portal": "maxima",
    "manual": true,
    "schedules": [
      {
        "cron": "50 */6 * * *",
        "human": "Every 6 hours at :50"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap catalogue pages walked (ad-hoc partial). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run (blank = drain the queue)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "1.0",
        "options": null
      },
      {
        "name": "workers",
        "description": "detail-fetch workers (concurrency; raise for a one-time backfill)",
        "required": false,
        "type": "string",
        "default": "2",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "maxima-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_maxima.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_maxima.yml"
  },
  {
    "filename": "scrape_mmreality.yml",
    "name": "Scraping: M&M Reality scraper (pilot)",
    "description": "Scheduled (every 6h) + manual scraper for mmreality.cz on the shared portal framework. M&M Reality is a server-rendered HTML portal whose detail pages embed a complete structured estate object (a Vue `:property` prop): the index walk pages the mixed-category /nemovitosti/ results and enqueues new/price- changed ids into listing_detail_queue, then the detail drain fetches each listing page, decodes its :property JSON to a ScrapedListing, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + Tier-1 property matching).",
    "portal": "mmreality",
    "manual": true,
    "schedules": [
      {
        "cron": "50 */6 * * *",
        "human": "Every 6 hours at :50"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap index pages walked (pilot safety). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "20",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run",
        "required": false,
        "type": "string",
        "default": "2000",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "2.0",
        "options": null
      },
      {
        "name": "workers",
        "description": "detail-fetch workers (concurrency; raise for a one-time backfill)",
        "required": false,
        "type": "string",
        "default": "4",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "mmreality-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_mmreality.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_mmreality.yml"
  },
  {
    "filename": "scrape_price_stats.yml",
    "name": "Scraping: Sreality price stats (ceny-nemovitosti, weekly + manual)",
    "description": "Ingests the aggregate market statistics sreality publishes at /ceny-nemovitosti (NOT individual listings) into the price_stat_* tables. For each active dataset (one named filter set) × tracked municipality × {prodej, pronájem} it fetches the per-month series from the login-gated estate_prices JSON API, then recomputes the per-city derived metrics (CAGR growth, gross yield) + refreshes the map choropleth. Design: docs/design/price-stats-datasets.md.",
    "portal": null,
    "manual": true,
    "schedules": [
      {
        "cron": "0 4 * * 1",
        "human": "0 4 * * 1"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "mode",
        "description": "probe (test auth) | resolve (refresh localities) | full",
        "required": true,
        "type": "choice",
        "default": "full",
        "options": [
          "probe",
          "resolve",
          "full"
        ]
      },
      {
        "name": "dataset_id",
        "description": "Single dataset id to run (empty = all active datasets)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "start_year",
        "description": "Earliest year to fetch",
        "required": false,
        "type": "string",
        "default": "2015",
        "options": null
      },
      {
        "name": "window_years",
        "description": "CAGR window (years) for the derived growth metrics",
        "required": false,
        "type": "string",
        "default": "5",
        "options": null
      },
      {
        "name": "dry_run",
        "description": "Fetch + log but write nothing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SREALITY_LOGIN_EMAIL",
      "SREALITY_LOGIN_PASSWORD",
      "SREALITY_SESSION_COOKIE",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "price-stats",
    "cancelInProgress": false,
    "timeoutMinutes": 60,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_price_stats.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_price_stats.yml"
  },
  {
    "filename": "scrape_remax.yml",
    "name": "Scraping: RE/MAX scraper (pilot)",
    "description": "Scheduled (every 6h) + manual scraper for remax-czech.cz on the shared portal framework. RE/MAX is a national franchise catalogue (~7,900 listings) served as a single server-rendered search index (no JSON API, no per-category URL) split only by an offer-type flag (sale=1 prodej / sale=2 pronájem): the index walk pages each agenda and enqueues new/price-changed ids into listing_detail_queue, then the detail drain fetches each /reality/detail/{id}/ page, parses to a ScrapedListing, and ingests through db.ingest_scraped_listing (Tier-0 idempotency + singleton property).",
    "portal": "remax",
    "manual": true,
    "schedules": [
      {
        "cron": "40 */6 * * *",
        "human": "Every 6 hours at :40"
      }
    ],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "max_pages",
        "description": "cap search pages walked per agenda (ad-hoc partial). Blank = full walk.",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_detail",
        "description": "cap detail-drain claims this run (blank = per-portal config)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "max_seconds",
        "description": "wall-clock budget for the detail drain (seconds)",
        "required": false,
        "type": "string",
        "default": "1500",
        "options": null
      },
      {
        "name": "rate",
        "description": "detail-fetch requests/second ceiling",
        "required": false,
        "type": "string",
        "default": "2.0",
        "options": null
      },
      {
        "name": "workers",
        "description": "detail-fetch workers (concurrency; raise for a one-time backfill)",
        "required": false,
        "type": "string",
        "default": "4",
        "options": null
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": "remax-scrape",
    "cancelInProgress": false,
    "timeoutMinutes": 30,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/scrape_remax.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/scrape_remax.yml"
  },
  {
    "filename": "seed_condition_settings.yml",
    "name": "Data: seed condition settings (rubric + markers)",
    "description": "One-shot workflow that populates the two large app_settings rows created by migration 072 — `llm_condition_rubric` and `llm_condition_marker_dictionary` — from the committed JSON files (data/condition_rubric_v1.json + data/condition_markers_curated.json).",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Print sizes and exit without UPDATEing",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      }
    ],
    "secrets": [
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/seed_condition_settings.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/seed_condition_settings.yml"
  },
  {
    "filename": "seed_curated_cities.yml",
    "name": "Data: seed curated cities",
    "description": "One-shot workflow that geocodes the cities in data/obce_v_datech_2025.csv via Mapy.cz, then writes them into curated_cities + city_index_definitions + city_index_revisions + city_index_values (+ city_population from data/csu_population.json when present).",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "dry_run",
        "description": "Plan only — geocode, but skip DB writes",
        "required": false,
        "type": "choice",
        "default": "false",
        "options": [
          "false",
          "true"
        ]
      },
      {
        "name": "commit_geocodes",
        "description": "Commit data/curated_cities_geocoded.json back to the branch",
        "required": false,
        "type": "choice",
        "default": "true",
        "options": [
          "true",
          "false"
        ]
      }
    ],
    "secrets": [
      "MAPY_CZ_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 15,
    "permissions": "contents: write",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/seed_curated_cities.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/seed_curated_cities.yml"
  },
  {
    "filename": "smoke_agent.yml",
    "name": "Dev: agent smoke test",
    "description": "Manual invocation only. Runs scripts/smoke_agent.py against the real Supabase DB and a real LLM provider. Picks a recent Prague 2+kk rental by default; --sreality-id overrides. Real LLM credits are spent — typically under $0.10 per run.",
    "portal": null,
    "manual": true,
    "schedules": [],
    "onPush": false,
    "onPullRequest": false,
    "paths": null,
    "inputs": [
      {
        "name": "provider",
        "description": "LLM provider (anthropic or gemini)",
        "required": true,
        "type": "choice",
        "default": "anthropic",
        "options": [
          "anthropic",
          "gemini"
        ]
      },
      {
        "name": "sreality_id",
        "description": "Specific listing id to estimate (leave blank to pick a recent Prague 2+kk)",
        "required": false,
        "type": "string",
        "default": "",
        "options": null
      },
      {
        "name": "skill",
        "description": "Skill row name",
        "required": false,
        "type": "string",
        "default": "rental_estimator_v1",
        "options": null
      }
    ],
    "secrets": [
      "ANTHROPIC_API_KEY",
      "GEMINI_API_KEY",
      "SUPABASE_DB_URL"
    ],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": "contents: read",
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/smoke_agent.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/smoke_agent.yml"
  },
  {
    "filename": "test.yml",
    "name": "CI: tests",
    "description": "CI test suite, runs on every push and pull request. Two parallel jobs: a Python job (verifies the filter-registry and workflow-docs codegen are fresh, then runs pytest) and a frontend job (TypeScript type-check + vitest pure-function tests). This is the build gate for every branch.",
    "portal": null,
    "manual": false,
    "schedules": [],
    "onPush": true,
    "onPullRequest": true,
    "paths": null,
    "inputs": [],
    "secrets": [],
    "concurrencyGroup": null,
    "cancelInProgress": null,
    "timeoutMinutes": 5,
    "permissions": null,
    "runsUrl": "https://github.com/waiff/sreality/actions/workflows/test.yml",
    "sourceUrl": "https://github.com/waiff/sreality/blob/main/.github/workflows/test.yml"
  }
];
